$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1404798808155.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"306c71ac815a48cc80c0f89c4d761934",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF5F5F5},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"396977fbdc1d4c6aae2a6023b5a3547c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":110},
            "size":{
              "width":900,
              "height":428},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE1E1E1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f99f0d42a43471cb79a6abe0ba5e84c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":110},
                "size":{
                  "width":900,
                  "height":428},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE1E1E1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"e880a3178b524f91bfabff25c3eb09e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":723,
              "y":209},
            "size":{
              "width":298,
              "height":281},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37a42f5ed2ec4a96997451369d0e206c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":723,
                  "y":209},
                "size":{
                  "width":298,
                  "height":281},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u2.png"}},
{
          "id":"36e94413e4384108afe60d5b850c3363",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'TimesNewRomanPSMT', 'Times New Roman'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5375E1,
              "opacity":1},
            "location":{
              "x":263,
              "y":143},
            "size":{
              "width":157,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dcfa6c9d6f0470998ed6a607f58b28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'TimesNewRomanPSMT', 'Times New Roman'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5375E1,
                  "opacity":1},
                "location":{
                  "x":263,
                  "y":143},
                "size":{
                  "width":157,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a79ebe06402042a687bd1a7b3b0e7ece",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"9b3ccec187f446b1a8804d9888116ed6"},
{
          "id":"11557473e6c147f983ca8af0dd7114c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":207},
            "size":{
              "width":464,
              "height":284}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb92527b5c2403a91ce585ab2a2cfa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":207},
                "size":{
                  "width":464,
                  "height":284}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"37421640a3744c8fbb6dd82d3d39e459",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":296},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1<br> (If text on This equals &quot;jin&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"jin",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Roles to Facilitator",
                      "panelsToStates":[{
                          "panelPath":["220b638ec28443cb84365c714c4b5eef"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Roles to State1",
                      "panelsToStates":[{
                          "panelPath":["220b638ec28443cb84365c714c4b5eef"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"f6f6cf2e08804054be6e64abbfd0e7ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":355},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8b7724fb9b0b4795baa48a849ebc37fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica', 'Helvetica'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":758,
              "y":229},
            "size":{
              "width":57,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d981621d8a74fa1bc930247c5e0b17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica', 'Helvetica'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":758,
                  "y":229},
                "size":{
                  "width":57,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d1a8ed0ea5d4476801692524e2d1513",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica', 'Helvetica'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":759,
              "y":275},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0351355efb634ed39bafcd501cd41d63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica', 'Helvetica'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":759,
                  "y":275},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba227482acb04c4f9789867cd141e652",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica', 'Helvetica'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":759,
              "y":335},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce95ceacf3f244c4b94742bccd86894a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica', 'Helvetica'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":759,
                  "y":335},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e0b39f61fa441e3b06d21cf7bad4cf6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":441},
            "size":{
              "width":108,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ff094a5f6fb481d90856950d736838e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":759,
                  "y":441},
                "size":{
                  "width":108,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Introduction in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"introduction.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u27.png"}},
{
          "id":"220b638ec28443cb84365c714c4b5eef",
          "label":"Roles",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":398},
            "size":{
              "width":221,
              "height":32}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"187aa080946449979cb95f4ab7ce3b39",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"fa789fc217a34e2d82a9794f4c8185ac",
              "label":"Facilitator",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"259de6f0f6b94cfaaea61c814b763fb3",
                  "label":"",
                  "parentDynamicPanel":"220b638ec28443cb84365c714c4b5eef",
                  "panelIndex":1,
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "9b3ccec187f446b1a8804d9888116ed6":{
      "packageId":"9b3ccec187f446b1a8804d9888116ed6",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"451841258e7947618bef0b4a47491b6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF2F4E9B},
              "size":{
                "width":1300,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e79f9fda3a9843fb971112e73b5dcd7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF2F4E9B},
                  "size":{
                    "width":1300,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u7.png"}},
{
            "id":"159d422844fb4e44bc20be4cdcebf6c4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a4a8f2603319495da78e1a7f0c572457",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u9.png"}},
{
            "id":"0cedba19834643448c03d22205bec628",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bebd04495ce54eb8887e63f320375a00",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f888f0f79e724555bf6288cd2d5c58bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1925fa813f5f4067b9aade84321e7ac7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1c0bb230002a405eb0877dfefbd5e517",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"c605202ce5a143f6a916795ebcaa977b",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "396977fbdc1d4c6aae2a6023b5a3547c":{
      "scriptId":"u0"},
    "5f99f0d42a43471cb79a6abe0ba5e84c":{
      "scriptId":"u1"},
    "e880a3178b524f91bfabff25c3eb09e3":{
      "scriptId":"u2"},
    "37a42f5ed2ec4a96997451369d0e206c":{
      "scriptId":"u3"},
    "36e94413e4384108afe60d5b850c3363":{
      "scriptId":"u4"},
    "8dcfa6c9d6f0470998ed6a607f58b28b":{
      "scriptId":"u5"},
    "a79ebe06402042a687bd1a7b3b0e7ece":{
      "scriptId":"u6",
      "451841258e7947618bef0b4a47491b6a":{
        "scriptId":"u7"},
      "e79f9fda3a9843fb971112e73b5dcd7b":{
        "scriptId":"u8"},
      "159d422844fb4e44bc20be4cdcebf6c4":{
        "scriptId":"u9"},
      "a4a8f2603319495da78e1a7f0c572457":{
        "scriptId":"u10"},
      "0cedba19834643448c03d22205bec628":{
        "scriptId":"u11"},
      "bebd04495ce54eb8887e63f320375a00":{
        "scriptId":"u12"},
      "f888f0f79e724555bf6288cd2d5c58bf":{
        "scriptId":"u13"},
      "1925fa813f5f4067b9aade84321e7ac7":{
        "scriptId":"u14"},
      "1c0bb230002a405eb0877dfefbd5e517":{
        "scriptId":"u15"},
      "c605202ce5a143f6a916795ebcaa977b":{
        "scriptId":"u16"}},
    "11557473e6c147f983ca8af0dd7114c7":{
      "scriptId":"u17"},
    "cbb92527b5c2403a91ce585ab2a2cfa4":{
      "scriptId":"u18"},
    "37421640a3744c8fbb6dd82d3d39e459":{
      "scriptId":"u19"},
    "f6f6cf2e08804054be6e64abbfd0e7ef":{
      "scriptId":"u20"},
    "8b7724fb9b0b4795baa48a849ebc37fc":{
      "scriptId":"u21"},
    "8d981621d8a74fa1bc930247c5e0b17b":{
      "scriptId":"u22"},
    "2d1a8ed0ea5d4476801692524e2d1513":{
      "scriptId":"u23"},
    "0351355efb634ed39bafcd501cd41d63":{
      "scriptId":"u24"},
    "ba227482acb04c4f9789867cd141e652":{
      "scriptId":"u25"},
    "ce95ceacf3f244c4b94742bccd86894a":{
      "scriptId":"u26"},
    "8e0b39f61fa441e3b06d21cf7bad4cf6":{
      "scriptId":"u27"},
    "1ff094a5f6fb481d90856950d736838e":{
      "scriptId":"u28"},
    "220b638ec28443cb84365c714c4b5eef":{
      "scriptId":"u29"},
    "259de6f0f6b94cfaaea61c814b763fb3":{
      "scriptId":"u30"}}});