$axure.loadCurrentPage({
  "url":"seminarmanagement.html",
  "generationDate":new Date(1400123444086.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"973d62f5299a480aaeeb3a7f152de92e",
    "type":"Axure:Page",
    "name":"SeminarManagement",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be579c40fb524f6cb88c81589db1a59c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":460},
            "size":{
              "width":900,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e738708f73a040c08d8bcd73ef168c3a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"466c95154614418c882abfc690cf3d00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"851d25f865834fd0974be97486a71dab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bdde3a6719e041b4bfcc4c6d30a5d947",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"01d05b0a74314b6fb357fa1bb9fa39a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1716bce6d84747b2bc26613ced086d3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"c6856a68f6ea4ac88ef22ead137a5682",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db48caf215224b35837f9ea139c7304f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"fb838d23bd044879accbe947b2820e6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac67e9e7e25147c9a8db16eb2a53f149",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"bd7808cb2e26435b85880bb66fd45fc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7591d4aa6364c99958d1ba6d9bd08a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"a70c5a18945e49ef865438ae9f919e8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcd41d885cbd4856890ab7902cb58e47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"9671c7ce2cbc4b259637cf0e3b45ace0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06762e3b02824e2597ebde9d66f99f72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"ed154d2d183c4775a5688e086b0f8b40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"874d240d602e429e8d265c4f86e568b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"c674e86d85a74ba289e70f56c04170d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6d51d3de4aa4395a8d4caf5dfcd2f50",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"a3accf9a7b304323a7ea9f1a60c3dbaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06b65f6922c840a59418b8c65d9f2268",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"cd23600db4e8415885763eae1cbb610b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e88d50a18fe2448f81df4842cdf35149",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"562aca1dbcec4273b3fbf99d72424155",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"606a9aae2b47406f8420b68e671a234d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"2dfa2862a0f64d0da909cc2d21553bc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f96eee60299d4f5a8d876cd8c4a310f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"17e39e9cda744acaa862aa390266c06f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f082ad44f9a940399df363153398ab9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"57416d4a8ff640fdbbe90d8d0fbc19da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"333676b063ab47328b1e9dde96e063f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"b320e41b37e349afa202a24704c4927a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cdc8e4e6e75245bab6d08c33f93742d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"6b451ac6b43049ec87bbfac4ce0aa5e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea759551b35b48ea8bd9e254ad6bfacb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"69ae3732abbf4fdb8d31b75e948d9a21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7356980c1a90410c9900756dabfffbb8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"dafd67bffa8240dfbf2aa30c505e4bbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fed7fd9644f0455196b94bfcd1ce30e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"3b54534ac3444157a0ac5519fbb161bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45a861bb465c4dd28dec749cd5cf0de7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"ff1354fb0a664feca97e8eaf020594da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13a9dc65ee514517b33917e3572080c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"e4ba28952d384869836f505a15097fa1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05a37520889146ffaecc8effee6a4296",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"1c94fad1cb2e4273ad0db7ac29a7f238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e1f7cc0ef484db0b107bdee7f8702f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"17fe978bfdcb4ebaae145e17b322a02c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba5b04f7f1104ef69ebb9f0fe58a3167",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u17.png"}},
{
              "id":"3636d572bfa447de9be15b5de10459be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7790314637554c36897310c8ddb22165",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u35.png"}},
{
              "id":"dadb9bc4a2f543d99a1368ff7f52e19b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77669d7b79b74fc48b433c5867875c22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u53.png"}}]},
{
          "id":"3f17d9dab7e44ed59e864a45765a9e4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":10},
            "size":{
              "width":860,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81c53834544545b6a9e78dbcbe8347d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":10},
                "size":{
                  "width":860,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/seminarmanagement/u55.png"}},
{
          "id":"5ff5836a3c2c46c3a928e6f540a75754",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":125},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4228591228e04a8598f355b86ae97380",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":30},
            "size":{
              "width":95,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc36fcdc3a6d463895dd24bdc2d5d46d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":30},
                "size":{
                  "width":95,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c59035b0ee1d43938cce1a821d1e0f45",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"301ccf27204345b683034f9927b27cf3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":80},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b32764db79e54d58b4dcecf40dffc8fe",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":81},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2e655a97c9fb4821ba6af48acc67a565",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":83},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"596592354c2049f2b6f10e0b8f42dc79",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":300},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8732f10dbd2e4b8185757dbe4cda8b72",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":665,
              "y":494.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open StudentManagement in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"studentmanagement.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9297c9ef57ac4a26b724fa77363c5f24",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":494},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open seminarsetting in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"seminarsetting.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"19de1295535041c1b099ca225d2178f7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":210},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "be579c40fb524f6cb88c81589db1a59c":{
      "scriptId":"u0"},
    "e738708f73a040c08d8bcd73ef168c3a":{
      "scriptId":"u1"},
    "466c95154614418c882abfc690cf3d00":{
      "scriptId":"u2"},
    "c6856a68f6ea4ac88ef22ead137a5682":{
      "scriptId":"u3"},
    "db48caf215224b35837f9ea139c7304f":{
      "scriptId":"u4"},
    "a70c5a18945e49ef865438ae9f919e8e":{
      "scriptId":"u5"},
    "dcd41d885cbd4856890ab7902cb58e47":{
      "scriptId":"u6"},
    "c674e86d85a74ba289e70f56c04170d6":{
      "scriptId":"u7"},
    "a6d51d3de4aa4395a8d4caf5dfcd2f50":{
      "scriptId":"u8"},
    "562aca1dbcec4273b3fbf99d72424155":{
      "scriptId":"u9"},
    "606a9aae2b47406f8420b68e671a234d":{
      "scriptId":"u10"},
    "57416d4a8ff640fdbbe90d8d0fbc19da":{
      "scriptId":"u11"},
    "333676b063ab47328b1e9dde96e063f3":{
      "scriptId":"u12"},
    "69ae3732abbf4fdb8d31b75e948d9a21":{
      "scriptId":"u13"},
    "7356980c1a90410c9900756dabfffbb8":{
      "scriptId":"u14"},
    "ff1354fb0a664feca97e8eaf020594da":{
      "scriptId":"u15"},
    "13a9dc65ee514517b33917e3572080c0":{
      "scriptId":"u16"},
    "17fe978bfdcb4ebaae145e17b322a02c":{
      "scriptId":"u17"},
    "ba5b04f7f1104ef69ebb9f0fe58a3167":{
      "scriptId":"u18"},
    "851d25f865834fd0974be97486a71dab":{
      "scriptId":"u19"},
    "bdde3a6719e041b4bfcc4c6d30a5d947":{
      "scriptId":"u20"},
    "fb838d23bd044879accbe947b2820e6b":{
      "scriptId":"u21"},
    "ac67e9e7e25147c9a8db16eb2a53f149":{
      "scriptId":"u22"},
    "9671c7ce2cbc4b259637cf0e3b45ace0":{
      "scriptId":"u23"},
    "06762e3b02824e2597ebde9d66f99f72":{
      "scriptId":"u24"},
    "a3accf9a7b304323a7ea9f1a60c3dbaa":{
      "scriptId":"u25"},
    "06b65f6922c840a59418b8c65d9f2268":{
      "scriptId":"u26"},
    "2dfa2862a0f64d0da909cc2d21553bc6":{
      "scriptId":"u27"},
    "f96eee60299d4f5a8d876cd8c4a310f1":{
      "scriptId":"u28"},
    "b320e41b37e349afa202a24704c4927a":{
      "scriptId":"u29"},
    "cdc8e4e6e75245bab6d08c33f93742d5":{
      "scriptId":"u30"},
    "dafd67bffa8240dfbf2aa30c505e4bbf":{
      "scriptId":"u31"},
    "fed7fd9644f0455196b94bfcd1ce30e8":{
      "scriptId":"u32"},
    "e4ba28952d384869836f505a15097fa1":{
      "scriptId":"u33"},
    "05a37520889146ffaecc8effee6a4296":{
      "scriptId":"u34"},
    "3636d572bfa447de9be15b5de10459be":{
      "scriptId":"u35"},
    "7790314637554c36897310c8ddb22165":{
      "scriptId":"u36"},
    "01d05b0a74314b6fb357fa1bb9fa39a4":{
      "scriptId":"u37"},
    "1716bce6d84747b2bc26613ced086d3d":{
      "scriptId":"u38"},
    "bd7808cb2e26435b85880bb66fd45fc3":{
      "scriptId":"u39"},
    "b7591d4aa6364c99958d1ba6d9bd08a3":{
      "scriptId":"u40"},
    "ed154d2d183c4775a5688e086b0f8b40":{
      "scriptId":"u41"},
    "874d240d602e429e8d265c4f86e568b1":{
      "scriptId":"u42"},
    "cd23600db4e8415885763eae1cbb610b":{
      "scriptId":"u43"},
    "e88d50a18fe2448f81df4842cdf35149":{
      "scriptId":"u44"},
    "17e39e9cda744acaa862aa390266c06f":{
      "scriptId":"u45"},
    "f082ad44f9a940399df363153398ab9d":{
      "scriptId":"u46"},
    "6b451ac6b43049ec87bbfac4ce0aa5e3":{
      "scriptId":"u47"},
    "ea759551b35b48ea8bd9e254ad6bfacb":{
      "scriptId":"u48"},
    "3b54534ac3444157a0ac5519fbb161bd":{
      "scriptId":"u49"},
    "45a861bb465c4dd28dec749cd5cf0de7":{
      "scriptId":"u50"},
    "1c94fad1cb2e4273ad0db7ac29a7f238":{
      "scriptId":"u51"},
    "7e1f7cc0ef484db0b107bdee7f8702f3":{
      "scriptId":"u52"},
    "dadb9bc4a2f543d99a1368ff7f52e19b":{
      "scriptId":"u53"},
    "77669d7b79b74fc48b433c5867875c22":{
      "scriptId":"u54"},
    "3f17d9dab7e44ed59e864a45765a9e4f":{
      "scriptId":"u55"},
    "81c53834544545b6a9e78dbcbe8347d8":{
      "scriptId":"u56"},
    "5ff5836a3c2c46c3a928e6f540a75754":{
      "scriptId":"u57"},
    "4228591228e04a8598f355b86ae97380":{
      "scriptId":"u58"},
    "cc36fcdc3a6d463895dd24bdc2d5d46d":{
      "scriptId":"u59"},
    "c59035b0ee1d43938cce1a821d1e0f45":{
      "scriptId":"u60"},
    "301ccf27204345b683034f9927b27cf3":{
      "scriptId":"u61"},
    "b32764db79e54d58b4dcecf40dffc8fe":{
      "scriptId":"u62"},
    "2e655a97c9fb4821ba6af48acc67a565":{
      "scriptId":"u63"},
    "596592354c2049f2b6f10e0b8f42dc79":{
      "scriptId":"u64"},
    "8732f10dbd2e4b8185757dbe4cda8b72":{
      "scriptId":"u65"},
    "9297c9ef57ac4a26b724fa77363c5f24":{
      "scriptId":"u66"},
    "19de1295535041c1b099ca225d2178f7":{
      "scriptId":"u67"}}});