$axure.loadCurrentPage({
  "url":"studentmanagement.html",
  "generationDate":new Date(1400493978829.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"239a165315174ea2966030e2f8b45beb",
    "type":"Axure:Page",
    "name":"StudentManagement",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01e9a32f20234ffb83e9eb085ac560e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":850,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ee0bc779ac4278a5173112408bb6c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":850,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/studentmanagement/u0.png"}},
{
          "id":"ecb486471cf74f7ab540f424c9019141",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"86919dfbd6884f76af577ce074b5517f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":183},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ddd4438b7dca4385b65459b1de491860",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":135},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5572665e1574493f97f441cf3aba020b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":135},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d9fdff58c23f463c97266950a5455d8c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":260},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"51dff7906e2946bc82afbfc690c16ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":130,
              "y":20},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc81f5437f544c3d91ec077d50852fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":130,
                  "y":20},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56b946e6d5d145128326f44a2e354c3a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":335},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45b87d72e8e9493f804df596378dc342",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":410},
            "size":{
              "width":780,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a24ffe54843458e82d22b4369b9aadd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"feed19efa503400b9c57be25a3ae87ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"f04d828ab222412c8be076b4a37dc058",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3b83958571f46fb8a308a293548a7c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"1d3ca4af8f154f3f9db5e47981e78b24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7caeb4154d634dbabbb35fa99ce9120a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"1e41d7e01a7840ca81503fbf446ee1fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d17ad73de2bf46fc969652ba37b976f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"90611084a4334c8d840ec68a806a4c71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0384c2af07040e19e271ac7918811c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"c12ace29a2064c52bc05f2210215a63b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce65ef588b344d1a937b389efaae403e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"8453746e6b6f4d108f080cab8d937120",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee0f9d825cf748cdbc83dcfd740d57d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"6b2abd10b70848618d388c5d45095f1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22c0ea5c17d649f095a406c8353c255b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"9190f356db4143d08080a41331f3d017",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c53ec7c5378c49c49052bb7424dd34df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"71c018e2a18a456eabd53298840bed03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a1fe820592d4263b348993a6a6f9f00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"56d5ed101295447cbf823ce6e0594a7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0d58f3da5644f868d4527a75e4a5117",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"25dc594c1548445ea95f5b04dc83ec84",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5cec446856fb45228ac8475f0929231a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"11dc68674a3646f68901dd973b37c9fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":650,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b60a2df6f6214088a3f78238c3868aff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":650,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u21.png"}},
{
              "id":"8d24361ccc6e40aaa0cd85e43e22ef33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":650,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"540f995517d54ebd89e5efa8f5eaf10e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":650,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u21.png"}},
{
              "id":"0f9a2036b85e43eab83a2f31cad80518",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":650,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"914cfd414cbf42538f5b7f1fea670fd0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":650,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u45.png"}},
{
              "id":"d70e03202fb84dbcadd7e1890307aa7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5863e73412946f88505f567dc97b5f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"a30189492b2f4d94875a1e1efff94412",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c34c4d599fc1440299f8f5cffda5ccb4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"b2c947805a3c484aa763c509bfc88ef2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d86e119352744786b71d3b27ee2c8582",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}}]},
{
          "id":"900edc317506421b965b95ea6b77f210",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":136.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b5c434317fee41cf8899eaa743685645",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":218},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "01e9a32f20234ffb83e9eb085ac560e1":{
      "scriptId":"u0"},
    "83ee0bc779ac4278a5173112408bb6c7":{
      "scriptId":"u1"},
    "ecb486471cf74f7ab540f424c9019141":{
      "scriptId":"u2"},
    "86919dfbd6884f76af577ce074b5517f":{
      "scriptId":"u3"},
    "ddd4438b7dca4385b65459b1de491860":{
      "scriptId":"u4"},
    "5572665e1574493f97f441cf3aba020b":{
      "scriptId":"u5"},
    "d9fdff58c23f463c97266950a5455d8c":{
      "scriptId":"u6"},
    "51dff7906e2946bc82afbfc690c16ed8":{
      "scriptId":"u7"},
    "bc81f5437f544c3d91ec077d50852fc3":{
      "scriptId":"u8"},
    "56b946e6d5d145128326f44a2e354c3a":{
      "scriptId":"u9"},
    "45b87d72e8e9493f804df596378dc342":{
      "scriptId":"u10"},
    "3a24ffe54843458e82d22b4369b9aadd":{
      "scriptId":"u11"},
    "feed19efa503400b9c57be25a3ae87ad":{
      "scriptId":"u12"},
    "1e41d7e01a7840ca81503fbf446ee1fc":{
      "scriptId":"u13"},
    "d17ad73de2bf46fc969652ba37b976f9":{
      "scriptId":"u14"},
    "d70e03202fb84dbcadd7e1890307aa7b":{
      "scriptId":"u15"},
    "b5863e73412946f88505f567dc97b5f6":{
      "scriptId":"u16"},
    "8453746e6b6f4d108f080cab8d937120":{
      "scriptId":"u17"},
    "ee0f9d825cf748cdbc83dcfd740d57d7":{
      "scriptId":"u18"},
    "71c018e2a18a456eabd53298840bed03":{
      "scriptId":"u19"},
    "3a1fe820592d4263b348993a6a6f9f00":{
      "scriptId":"u20"},
    "11dc68674a3646f68901dd973b37c9fe":{
      "scriptId":"u21"},
    "b60a2df6f6214088a3f78238c3868aff":{
      "scriptId":"u22"},
    "f04d828ab222412c8be076b4a37dc058":{
      "scriptId":"u23"},
    "d3b83958571f46fb8a308a293548a7c7":{
      "scriptId":"u24"},
    "90611084a4334c8d840ec68a806a4c71":{
      "scriptId":"u25"},
    "e0384c2af07040e19e271ac7918811c0":{
      "scriptId":"u26"},
    "a30189492b2f4d94875a1e1efff94412":{
      "scriptId":"u27"},
    "c34c4d599fc1440299f8f5cffda5ccb4":{
      "scriptId":"u28"},
    "6b2abd10b70848618d388c5d45095f1b":{
      "scriptId":"u29"},
    "22c0ea5c17d649f095a406c8353c255b":{
      "scriptId":"u30"},
    "56d5ed101295447cbf823ce6e0594a7e":{
      "scriptId":"u31"},
    "b0d58f3da5644f868d4527a75e4a5117":{
      "scriptId":"u32"},
    "8d24361ccc6e40aaa0cd85e43e22ef33":{
      "scriptId":"u33"},
    "540f995517d54ebd89e5efa8f5eaf10e":{
      "scriptId":"u34"},
    "1d3ca4af8f154f3f9db5e47981e78b24":{
      "scriptId":"u35"},
    "7caeb4154d634dbabbb35fa99ce9120a":{
      "scriptId":"u36"},
    "c12ace29a2064c52bc05f2210215a63b":{
      "scriptId":"u37"},
    "ce65ef588b344d1a937b389efaae403e":{
      "scriptId":"u38"},
    "b2c947805a3c484aa763c509bfc88ef2":{
      "scriptId":"u39"},
    "d86e119352744786b71d3b27ee2c8582":{
      "scriptId":"u40"},
    "9190f356db4143d08080a41331f3d017":{
      "scriptId":"u41"},
    "c53ec7c5378c49c49052bb7424dd34df":{
      "scriptId":"u42"},
    "25dc594c1548445ea95f5b04dc83ec84":{
      "scriptId":"u43"},
    "5cec446856fb45228ac8475f0929231a":{
      "scriptId":"u44"},
    "0f9a2036b85e43eab83a2f31cad80518":{
      "scriptId":"u45"},
    "914cfd414cbf42538f5b7f1fea670fd0":{
      "scriptId":"u46"},
    "900edc317506421b965b95ea6b77f210":{
      "scriptId":"u47"},
    "b5c434317fee41cf8899eaa743685645":{
      "scriptId":"u48"}}});