$axure.loadCurrentPage({
  "url":"demo.html",
  "generationDate":new Date(1404798807017.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1881d5a26edb47d88651c17a9c184eab",
    "type":"Axure:Page",
    "name":"DEMO",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bbd57532f9304713b52a20812b7e6744",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":800,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c717db7223f944abbe2c28e9a0fc04bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":800,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/demo/u0.png"}},
{
          "id":"741a335b9b3e427c9c6a0c8d0e18526f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":800,
              "height":530}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"996ac282d17e415391c3442bb5142f87",
              "label":"scene1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6ec3c5e85cae49b69cc41b3f9d400f20",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":13},
                    "size":{
                      "width":118,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b3693f595d44536a9b8e5355c7d31ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":13},
                        "size":{
                          "width":118,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"46b6a9153de44577ab4e9cd7a8810144",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":80},
                    "size":{
                      "width":402,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9aed0604480496b83748bc4e0ed9e3f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":80},
                        "size":{
                          "width":402,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a13f312b425c47ae86ce65737533de8e",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":237},
                    "size":{
                      "width":211,
                      "height":203}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f2789acd744405fbc445cccb3ba9deb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":237},
                        "size":{
                          "width":211,
                          "height":203}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/demo/u7.png"}},
{
                  "id":"a084f6be41bb4acab7d1f4acd17ce28c",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":240,
                      "y":240},
                    "size":{
                      "width":247,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd253daf9bf74c959f81b802773fad29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":240,
                          "y":240},
                        "size":{
                          "width":247,
                          "height":170}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/demo/u9.png"}},
{
                  "id":"621d318459204a0db21003f5e9b09b8b",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":510,
                      "y":240},
                    "size":{
                      "width":260,
                      "height":190}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3a08584c830424b95613b4cbb860996",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":510,
                          "y":240},
                        "size":{
                          "width":260,
                          "height":190}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/demo/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4b748d9c97294326a5f7aaf46f21ea5a",
              "label":"scene2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"77a5d807f96740aab1d0e541b626516b",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":13},
                    "size":{
                      "width":118,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b517ba0f6284d60bf3ff1c36a6233f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":13},
                        "size":{
                          "width":118,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9af4a9b8fede400f971843831347f8a8",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":80},
                    "size":{
                      "width":350,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"639f1098bcf9477ca13a18f0d12b1655",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":80},
                        "size":{
                          "width":350,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5197e99dff3247e4970e36c65ac96c62",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":59,
                      "y":220},
                    "size":{
                      "width":492,
                      "height":250}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f04b888de62645d7ba07aa8435d0bef5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":59,
                          "y":220},
                        "size":{
                          "width":492,
                          "height":250}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/demo/u17.png"}},
{
                  "id":"0c24bf232f6f4d9f89b68d79fb563811",
                  "label":"",
                  "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":629,
                      "y":255},
                    "size":{
                      "width":101,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4039140c7cdc4caabd6243cf6f036563",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"741a335b9b3e427c9c6a0c8d0e18526f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":629,
                          "y":255},
                        "size":{
                          "width":101,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "bbd57532f9304713b52a20812b7e6744":{
      "scriptId":"u0"},
    "c717db7223f944abbe2c28e9a0fc04bc":{
      "scriptId":"u1"},
    "741a335b9b3e427c9c6a0c8d0e18526f":{
      "scriptId":"u2"},
    "6ec3c5e85cae49b69cc41b3f9d400f20":{
      "scriptId":"u3"},
    "4b3693f595d44536a9b8e5355c7d31ac":{
      "scriptId":"u4"},
    "46b6a9153de44577ab4e9cd7a8810144":{
      "scriptId":"u5"},
    "e9aed0604480496b83748bc4e0ed9e3f":{
      "scriptId":"u6"},
    "a13f312b425c47ae86ce65737533de8e":{
      "scriptId":"u7"},
    "3f2789acd744405fbc445cccb3ba9deb":{
      "scriptId":"u8"},
    "a084f6be41bb4acab7d1f4acd17ce28c":{
      "scriptId":"u9"},
    "fd253daf9bf74c959f81b802773fad29":{
      "scriptId":"u10"},
    "621d318459204a0db21003f5e9b09b8b":{
      "scriptId":"u11"},
    "c3a08584c830424b95613b4cbb860996":{
      "scriptId":"u12"},
    "77a5d807f96740aab1d0e541b626516b":{
      "scriptId":"u13"},
    "2b517ba0f6284d60bf3ff1c36a6233f2":{
      "scriptId":"u14"},
    "9af4a9b8fede400f971843831347f8a8":{
      "scriptId":"u15"},
    "639f1098bcf9477ca13a18f0d12b1655":{
      "scriptId":"u16"},
    "5197e99dff3247e4970e36c65ac96c62":{
      "scriptId":"u17"},
    "f04b888de62645d7ba07aa8435d0bef5":{
      "scriptId":"u18"},
    "0c24bf232f6f4d9f89b68d79fb563811":{
      "scriptId":"u19"},
    "4039140c7cdc4caabd6243cf6f036563":{
      "scriptId":"u20"}}});