$axure.loadCurrentPage({
  "url":"help.html",
  "generationDate":new Date(1398839132670.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6b94d6b33064f6cb12652d7889dce2c",
    "type":"Axure:Page",
    "name":"Help",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c8f309b391304416bdacf3fefb693c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":68,
              "y":75},
            "size":{
              "width":142,
              "height":195}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bd07de0b88e4cef84a3264050d17331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":68,
                  "y":75},
                "size":{
                  "width":142,
                  "height":195}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c8f309b391304416bdacf3fefb693c64":{
      "scriptId":"u0"},
    "3bd07de0b88e4cef84a3264050d17331":{
      "scriptId":"u1"}}});