$axure.loadCurrentPage({
  "url":"distributormanagement.html",
  "generationDate":new Date(1404798819598.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc9d449351c6453bb5fef6a23e777938",
    "type":"Axure:Page",
    "name":"DistributorManagement",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"67eab28772a54d98b3095e939fa9fc1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":850,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb2c2ca4e034944951a97eba08c49db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":850,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/studentmanagement/u0.png"}},
{
          "id":"20fc2634dc764effb1f2cf78df0a021b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"86da2736a30d429f821e82d21b69a413",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":190},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fdf3c552d6a945b6880cd7aaf76f5685",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":134},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2930c51f78b34666b76ff4b1873582ae",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":135},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"57e7e81986d34430b0a5079de6e190cd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":137},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fb4b3d0b313f4aaead2ea17e6e6a45c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":130,
              "y":20},
            "size":{
              "width":142,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdab8c8d48fd4c2aba761596c1887272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":130,
                  "y":20},
                "size":{
                  "width":142,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e69ac2572c1f40b28557cc120665798d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":240},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fe929b7fc1194b369b00e24c41a1f033",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":305},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e54766d10d2845229eb9f961a66d0b1f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":410},
            "size":{
              "width":650,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0375c50a2848cfb48ff8c7cae88090",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ececfffadf0446ba7484ed4e74e67d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"461c85b018f941b383dcfe93f17461a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"471575fc17ac4113850e200ef579ae75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"3e81e557bf654c9e813b6d2cba29b10d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4ac897932e14a83b59d3b97541be84f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"08470932debc4079aefc1818477cdb13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"099f4c752df548a9b9abea93102b5a30",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"18a00b1327034e488525d0377150cf81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"784a853e317842b8869ea7556226e8df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"d1e6fd4d08a3416f83095b618f989216",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9519ba1516824e5c938200141fe72c0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":130,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"f8dc061b82a64e1094f53ab3672d6f39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ae46141022046ebbb2887a5300be62d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"6945e28e3bd44b0185f75c8b26fea20d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3c02ee455c8433c82075e3344637cbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"6f43de30e4df45cbbf5d78a46a918757",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb6789329ee74d2d9424f95de322f927",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"0ae64db4ac1c4e40b896161b5069afd2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a989d5243c514908bd1559baad987825",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"8f20ea22bfdd42b680f616e7fa8db403",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8908cc5277424cfdb7daa14285f402af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u11.png"}},
{
              "id":"4d493dc496df4de1825edc9086849f5d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"454b790dba1a40189546aae2d1368aac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u35.png"}},
{
              "id":"5a8e29bf07b64c83a00d7adff41098bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32107a7898ef44df91a9d7a2ae6f567b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u21.png"}},
{
              "id":"2fce8b6e5d554bbb9b103877a1a3059e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"607944d353b94bcfa99b6faf476b5ed5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u21.png"}},
{
              "id":"40e2ba0c86dc4afe9f70e98ea7ab4a19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":520,
                  "y":60},
                "size":{
                  "width":130,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62e84fb7c9574f48b0f67e23b3b5d4fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":520,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/studentmanagement/u45.png"}}]},
{
          "id":"f4437e6529154c328547626866e14137",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":245},
            "size":{
              "width":195,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81bce47bcf9477db52916803c6a1380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":245},
                "size":{
                  "width":195,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "67eab28772a54d98b3095e939fa9fc1e":{
      "scriptId":"u0"},
    "4fb2c2ca4e034944951a97eba08c49db":{
      "scriptId":"u1"},
    "20fc2634dc764effb1f2cf78df0a021b":{
      "scriptId":"u2"},
    "86da2736a30d429f821e82d21b69a413":{
      "scriptId":"u3"},
    "fdf3c552d6a945b6880cd7aaf76f5685":{
      "scriptId":"u4"},
    "2930c51f78b34666b76ff4b1873582ae":{
      "scriptId":"u5"},
    "57e7e81986d34430b0a5079de6e190cd":{
      "scriptId":"u6"},
    "fb4b3d0b313f4aaead2ea17e6e6a45c1":{
      "scriptId":"u7"},
    "bdab8c8d48fd4c2aba761596c1887272":{
      "scriptId":"u8"},
    "e69ac2572c1f40b28557cc120665798d":{
      "scriptId":"u9"},
    "fe929b7fc1194b369b00e24c41a1f033":{
      "scriptId":"u10"},
    "e54766d10d2845229eb9f961a66d0b1f":{
      "scriptId":"u11"},
    "ee0375c50a2848cfb48ff8c7cae88090":{
      "scriptId":"u12"},
    "4ececfffadf0446ba7484ed4e74e67d7":{
      "scriptId":"u13"},
    "08470932debc4079aefc1818477cdb13":{
      "scriptId":"u14"},
    "099f4c752df548a9b9abea93102b5a30":{
      "scriptId":"u15"},
    "f8dc061b82a64e1094f53ab3672d6f39":{
      "scriptId":"u16"},
    "4ae46141022046ebbb2887a5300be62d":{
      "scriptId":"u17"},
    "0ae64db4ac1c4e40b896161b5069afd2":{
      "scriptId":"u18"},
    "a989d5243c514908bd1559baad987825":{
      "scriptId":"u19"},
    "5a8e29bf07b64c83a00d7adff41098bd":{
      "scriptId":"u20"},
    "32107a7898ef44df91a9d7a2ae6f567b":{
      "scriptId":"u21"},
    "461c85b018f941b383dcfe93f17461a4":{
      "scriptId":"u22"},
    "471575fc17ac4113850e200ef579ae75":{
      "scriptId":"u23"},
    "18a00b1327034e488525d0377150cf81":{
      "scriptId":"u24"},
    "784a853e317842b8869ea7556226e8df":{
      "scriptId":"u25"},
    "6945e28e3bd44b0185f75c8b26fea20d":{
      "scriptId":"u26"},
    "c3c02ee455c8433c82075e3344637cbc":{
      "scriptId":"u27"},
    "8f20ea22bfdd42b680f616e7fa8db403":{
      "scriptId":"u28"},
    "8908cc5277424cfdb7daa14285f402af":{
      "scriptId":"u29"},
    "2fce8b6e5d554bbb9b103877a1a3059e":{
      "scriptId":"u30"},
    "607944d353b94bcfa99b6faf476b5ed5":{
      "scriptId":"u31"},
    "3e81e557bf654c9e813b6d2cba29b10d":{
      "scriptId":"u32"},
    "a4ac897932e14a83b59d3b97541be84f":{
      "scriptId":"u33"},
    "d1e6fd4d08a3416f83095b618f989216":{
      "scriptId":"u34"},
    "9519ba1516824e5c938200141fe72c0f":{
      "scriptId":"u35"},
    "6f43de30e4df45cbbf5d78a46a918757":{
      "scriptId":"u36"},
    "fb6789329ee74d2d9424f95de322f927":{
      "scriptId":"u37"},
    "4d493dc496df4de1825edc9086849f5d":{
      "scriptId":"u38"},
    "454b790dba1a40189546aae2d1368aac":{
      "scriptId":"u39"},
    "40e2ba0c86dc4afe9f70e98ea7ab4a19":{
      "scriptId":"u40"},
    "62e84fb7c9574f48b0f67e23b3b5d4fc":{
      "scriptId":"u41"},
    "f4437e6529154c328547626866e14137":{
      "scriptId":"u42"},
    "b81bce47bcf9477db52916803c6a1380":{
      "scriptId":"u43"}}});