$axure.loadCurrentPage({
  "url":"questionnaire.html",
  "generationDate":new Date(1398317601425.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"efe9aa5df63541258cb503c9cf3f4881",
    "type":"Axure:Page",
    "name":"Questionnaire",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0e5b15f3631a40c9ab18653720892965",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"},
{
          "id":"f2ae0c5cdfbe43f1ab4866e65768e2a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":270,
              "y":80},
            "size":{
              "width":962,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d95cbb444f41b28d5d9e43ad8785d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":270,
                  "y":80},
                "size":{
                  "width":962,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d753f5541b2c4033ad063629976d8293",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":170},
            "size":{
              "width":570,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f8ccc70560463782aad0e216c915d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":170},
                "size":{
                  "width":570,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/questionnaire/u11.png"}},
{
          "id":"653659b0c9604e8e9f41fc1dc1766429",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":338,
              "y":190},
            "size":{
              "width":152,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a82d820310a463586c225189d551859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":338,
                  "y":190},
                "size":{
                  "width":152,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"952da113b6f04ab393edc0e519b2fc10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":890,
              "y":250},
            "size":{
              "width":330,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf29f776d414890bfddf1896ed9e524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":890,
                  "y":250},
                "size":{
                  "width":330,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/questionnaire/u15.png"}},
{
          "id":"63a0aed614d34e7a96052595dbfeacb3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":690},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"114610270477418d8bd2730b9255303a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":7.5}},
          "adaptiveStyles":{
},
          "masterId":"dbb0efc8e6d5469e835ac93a2e4814dc"}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "size":{
                "width":1370,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "size":{
                    "width":1370,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1236,
                "y":12},
              "size":{
                "width":113,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1236,
                    "y":12},
                  "size":{
                    "width":113,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "location":{
                "x":1150,
                "y":9},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "location":{
                "x":1020,
                "y":9},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":20,
                "y":12},
              "size":{
                "width":72,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":20,
                    "y":12},
                  "size":{
                    "width":72,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "dbb0efc8e6d5469e835ac93a2e4814dc":{
      "packageId":"dbb0efc8e6d5469e835ac93a2e4814dc",
      "type":"Axure:Master",
      "name":"UserMainNav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2a8a9e57fec4399aa5a983df98f5b99",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":20},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5394cfc481fd44608f321d06cb5c0490",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":205,
                "y":20},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"57c9e61be4c047e2b6f97da8bd5c9332",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":470,
                "y":20},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Result in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"result.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2dd631228acb42659a1a3dfc8bb0c56c",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":340,
                "y":20},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "0e5b15f3631a40c9ab18653720892965":{
      "scriptId":"u0",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u1"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u2"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u3"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u4"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u5"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u6"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u7"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u8"}},
    "f2ae0c5cdfbe43f1ab4866e65768e2a9":{
      "scriptId":"u9"},
    "89d95cbb444f41b28d5d9e43ad8785d6":{
      "scriptId":"u10"},
    "d753f5541b2c4033ad063629976d8293":{
      "scriptId":"u11"},
    "f5f8ccc70560463782aad0e216c915d6":{
      "scriptId":"u12"},
    "653659b0c9604e8e9f41fc1dc1766429":{
      "scriptId":"u13"},
    "9a82d820310a463586c225189d551859":{
      "scriptId":"u14"},
    "952da113b6f04ab393edc0e519b2fc10":{
      "scriptId":"u15"},
    "9cf29f776d414890bfddf1896ed9e524":{
      "scriptId":"u16"},
    "63a0aed614d34e7a96052595dbfeacb3":{
      "scriptId":"u17"},
    "114610270477418d8bd2730b9255303a":{
      "scriptId":"u18",
      "f2a8a9e57fec4399aa5a983df98f5b99":{
        "scriptId":"u19"},
      "5394cfc481fd44608f321d06cb5c0490":{
        "scriptId":"u20"},
      "57c9e61be4c047e2b6f97da8bd5c9332":{
        "scriptId":"u21"},
      "2dd631228acb42659a1a3dfc8bb0c56c":{
        "scriptId":"u22"}}}});