var userRoleModel = require('../api/models/user/userrole.js');
var mongoose = require('mongoose');

module.exports = [
    {
        "username": "hcd_administrator",
        "password": "admin1234@hcd",
        "email": "hcd_administrator@hcdlearning.com",
        "mobilePhone": "13916502743",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "role": userRoleModel.roleList.admin.id,
        "activated": true,
        "emailActivated": true,
        "emailActivateToken": "efe5ceba-fd21-445e-86b6-c5fa64f3c694"
    },
    {
        "_id": mongoose.Types.ObjectId("54609f0c700a570813b1353f"),
        "username": "hcd_distributor",
        "password": "distributor@hcd5678",
        "email": "hcd_distributor@hcdlearning.com",
        "mobilePhone": "13916502743",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "district": "Ren Min Lu",
        "street": "",
        "idcardNumber": "",
        "numOfUsedLicense": 0,
        "numOfLicense": 500000,
        "role": userRoleModel.roleList.distributor.id,
        "activated": true,
        "emailActivated": true,
        "emailActivateToken": "efe5ceba-fd21-445e-86b6-c5fa64f3c694"
    },
    {
        "_id": mongoose.Types.ObjectId("54609fb2700a570813b13540"),
        "username": "hcd_facilitator",
        "password": "hcdfacilitator@9876",
        "email": "hcd_facilitator@hcdlearning.com",
        "mobilePhone": "13916502743",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "distributorId": "54609f0c700a570813b1353f",
        "numOfUsedLicense": 0,
        "numOfLicense": 100000,
        "role": userRoleModel.roleList.facilitator.id,
        "activated": true,
        "emailActivated": true,
        "emailActivateToken": "efe5ceba-fd21-445e-86b6-c5fa64f3c694"
    },
    {
        "_id": mongoose.Types.ObjectId("54d834bdeaf05dbd048120f8"),
        "username": "b2c_facilitator",
        "password": "hcdfacilitator@9876",
        "email": "b2c_facilitator@hcdlearning.com",
        "mobilePhone": "13564568304",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "distributorId": "54609f0c700a570813b1353f",
        "numOfUsedLicense": 0,
        "numOfLicense": 1000000000,
        "role": userRoleModel.roleList.facilitator.id,
        "activated": true,
        "emailActivated": true,
        "emailActivateToken": "efe5ceba-fd21-445e-86b6-c5fa64f3c694"
    },
    {
        "username": "sunyun",
        "email": "yunsun@hcdlearning.com",
        "mobilePhone": "13817304511",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "password": "123456",
        "facilitatorId": "54609fb2700a570813b13540",
        "idcardNumber": "321181198502273515",
        "occupation": "Student",
        "firstName": "yun",
        "lastName": "sun",
        "organizationOrUniversity": "",
        "majorsDegree": "",
        "studentType": 10,
        "role": userRoleModel.roleList.student.id,
        "activated": true,
        "emailActivated": false
    },
    {
        "username": "jinwang",
        "email": "jinwang@hcdlearning.com",
        "mobilePhone": "13564568304",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "password": "123456",
        "facilitatorId": "54609fb2700a570813b13540",
        "idcardNumber": "321181198502273515",
        "occupation": "Student",
        "firstName": "jin",
        "lastName": "wang",
        "organizationOrUniversity": "",
        "majorsDegree": "",
        "studentType": 10,
        "role": userRoleModel.roleList.student.id,
        "activated": true,
        "emailActivated": false
    },
    {
        "username": "sunhao",
        "email": "haosun@hcdlearning.com",
        "mobilePhone": "18019419955",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "password": "123456",
        "facilitatorId": "54609fb2700a570813b13540",
        "idcardNumber": "321181198502273515",
        "occupation": "Student",
        "firstName": "hao",
        "lastName": "sun",
        "organizationOrUniversity": "",
        "majorsDegree": "",
        "studentType": 10,
        "role": userRoleModel.roleList.student.id,
        "activated": true,
        "emailActivated": false
    },
    {
        "username": "anilraparla",
        "email": "anilraparla@hcdlearning.com",
        "mobilePhone": "13916502743",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "password": "123456",
        "facilitatorId": "54609fb2700a570813b13540",
        "idcardNumber": "321181198502273515",
        "occupation": "Student",
        "firstName": "anil",
        "lastName": "anil",
        "organizationOrUniversity": "",
        "majorsDegree": "",
        "studentType": 10,
        "role": userRoleModel.roleList.student.id,
        "activated": true,
        "emailActivated": false
    },
    {
        "username": "yuekecheng",
        "email": "clarkyue@hcdlearning.com",
        "mobilePhone": "15900719671",
        "country": "China",
        "state": "shanghai",
        "city": "shanghai",
        "password": "123456",
        "facilitatorId": "54609fb2700a570813b13540",
        "idcardNumber": "321181198502273515",
        "occupation": "Student",
        "firstName": "clark",
        "lastName": "yue",
        "organizationOrUniversity": "",
        "majorsDegree": "",
        "studentType": 10,
        "role": userRoleModel.roleList.student.id,
        "activated": true,
        "emailActivated": false
    }
];