$axure.loadCurrentPage({
  "url":"introduction.html",
  "generationDate":new Date(1399955987106),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3149991a65104aac9cb87af805c382ba",
    "type":"Axure:Page",
    "name":"Introduction",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88d6d9924fb04554b5502ff4fc9ee332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":86},
            "size":{
              "width":316,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71cd7abd5473468990d4adca0ff3e4e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":86},
                "size":{
                  "width":316,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf7869f7f1ef4034a8f8dbe20e85aa63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":144},
            "size":{
              "width":1060,
              "height":500},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f634a18e907942c0bc096518c64e2813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":144},
                "size":{
                  "width":1060,
                  "height":500},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0E0E0}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/introduction/u2.png"}},
{
          "id":"6138fb0d30d7446fa1a3bbf997a6d6e9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":579},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open CompanyInfo in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"companyinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"82dc08b6ea2e4b25ba7478fe51f309c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":61,
              "y":239},
            "size":{
              "width":156,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b960fa2ecd54aa990e9a0158d107f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":61,
                  "y":239},
                "size":{
                  "width":156,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3e7bd6afa344087ae5d2c72a585493a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":64,
              "y":261},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d72571d56489495da48c26289b1dcb98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":64,
                  "y":261},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc5fcbc4a2242c5b1b22cd86456a5c0",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":304},
            "size":{
              "width":297,
              "height":230}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"http://www.youtube.com/embed/JBkGOPR3-nA",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"98a210d43b2d4cfaa29f4a8b558570df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":413,
              "y":239},
            "size":{
              "width":156,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ac463479af4db0ae83ba6d03e1a19c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":413,
                  "y":239},
                "size":{
                  "width":156,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b49e8fd373f24bd192ef071d767a6297",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":415,
              "y":261},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"357c57cb6960434e9c4e98312e3fece5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":415,
                  "y":261},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b97ccb07bc14dc4bbf428ec5f5427ce",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":304},
            "size":{
              "width":298,
              "height":230}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"http://www.youtube.com/embed/TRrL5j3MIvo",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"758fc92dd8d4433488f4057066b41e3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":752,
              "y":239},
            "size":{
              "width":156,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1752c38dff4f0a8a6f471fc6e89715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":752,
                  "y":239},
                "size":{
                  "width":156,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cd8088df2154e5287ecd7bc510e6e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":756,
              "y":261},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae3e26dd5b4443ca6fae108b9e128d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":756,
                  "y":261},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05e73b27e4d949c680c69f0b37d3ed55",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":304},
            "size":{
              "width":278,
              "height":230}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"http://www.youtube.com/embed/rlNmYgNdOkM",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"5c04fd4638f84621bf8642ea5db7e251",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "size":{
                "width":1301,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF294590},
                  "size":{
                    "width":1301,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"f1138e4bb64a4b03a9c6dc5d544ec919",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"888ba27679964561b0d5cb2a0ef3c9b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u27.png"}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b79d47f0fac44b12b3883c52e1e972ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4B67AE},
              "location":{
                "x":203,
                "y":1},
              "size":{
                "width":73,
                "height":40},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73173e2d2f9942cc95bb9e59f7e1d295",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4B67AE},
                  "location":{
                    "x":203,
                    "y":1},
                  "size":{
                    "width":73,
                    "height":40},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u31.png"}},
{
            "id":"a19273aad5e84f14b1fa81e5785797c6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":202,
                "y":39},
              "size":{
                "width":74,
                "height":10}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaaab34ad5a9472aa24182c8c888f172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":202,
                    "y":39},
                  "size":{
                    "width":74,
                    "height":10}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u33.png"}},
{
            "id":"59fe3b170417467e9815eada63bdbdf2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":221,
                "y":17},
              "size":{
                "width":37,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2003098ee0234a058a13919dad275e07",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":221,
                    "y":17},
                  "size":{
                    "width":37,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"131dcb64c5b64eaf9727db0ff5da22a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":304,
                "y":17},
              "size":{
                "width":43,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57955a7f69894cfe91133a475b6d8f6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":304,
                    "y":17},
                  "size":{
                    "width":43,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bebfd875fda4c26adb79875f309dca8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":393,
                "y":17},
              "size":{
                "width":35,
                "height":1}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8672a055a85f4a3ea48a54377f909e7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":393,
                    "y":17},
                  "size":{
                    "width":35,
                    "height":1}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ViewHistoryScore in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"viewhistoryscore.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4dc0d1b9cfb74e6ea7e30068da017d5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":474,
                "y":17},
              "size":{
                "width":54,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6599a0e13f6b4ea49a3d527489612b2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":17},
                  "size":{
                    "width":54,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1087cb033ba644918269a0311bd5ab5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"9px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":431,
                "y":12},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce0a950f883342d4ab6d1be3cd0d810c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"9px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":431,
                    "y":12},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "88d6d9924fb04554b5502ff4fc9ee332":{
      "scriptId":"u0"},
    "71cd7abd5473468990d4adca0ff3e4e6":{
      "scriptId":"u1"},
    "bf7869f7f1ef4034a8f8dbe20e85aa63":{
      "scriptId":"u2"},
    "f634a18e907942c0bc096518c64e2813":{
      "scriptId":"u3"},
    "6138fb0d30d7446fa1a3bbf997a6d6e9":{
      "scriptId":"u4"},
    "82dc08b6ea2e4b25ba7478fe51f309c0":{
      "scriptId":"u5"},
    "6b960fa2ecd54aa990e9a0158d107f09":{
      "scriptId":"u6"},
    "a3e7bd6afa344087ae5d2c72a585493a":{
      "scriptId":"u7"},
    "d72571d56489495da48c26289b1dcb98":{
      "scriptId":"u8"},
    "9bc5fcbc4a2242c5b1b22cd86456a5c0":{
      "scriptId":"u9"},
    "98a210d43b2d4cfaa29f4a8b558570df":{
      "scriptId":"u10"},
    "97ac463479af4db0ae83ba6d03e1a19c":{
      "scriptId":"u11"},
    "b49e8fd373f24bd192ef071d767a6297":{
      "scriptId":"u12"},
    "357c57cb6960434e9c4e98312e3fece5":{
      "scriptId":"u13"},
    "5b97ccb07bc14dc4bbf428ec5f5427ce":{
      "scriptId":"u14"},
    "758fc92dd8d4433488f4057066b41e3f":{
      "scriptId":"u15"},
    "bd1752c38dff4f0a8a6f471fc6e89715":{
      "scriptId":"u16"},
    "4cd8088df2154e5287ecd7bc510e6e8a":{
      "scriptId":"u17"},
    "7ae3e26dd5b4443ca6fae108b9e128d8":{
      "scriptId":"u18"},
    "05e73b27e4d949c680c69f0b37d3ed55":{
      "scriptId":"u19"},
    "5c04fd4638f84621bf8642ea5db7e251":{
      "scriptId":"u20",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u21"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u22"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u23"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u24"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u25"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u26"},
      "f1138e4bb64a4b03a9c6dc5d544ec919":{
        "scriptId":"u27"},
      "888ba27679964561b0d5cb2a0ef3c9b2":{
        "scriptId":"u28"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u29"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u30"},
      "b79d47f0fac44b12b3883c52e1e972ca":{
        "scriptId":"u31"},
      "73173e2d2f9942cc95bb9e59f7e1d295":{
        "scriptId":"u32"},
      "a19273aad5e84f14b1fa81e5785797c6":{
        "scriptId":"u33"},
      "eaaab34ad5a9472aa24182c8c888f172":{
        "scriptId":"u34"},
      "59fe3b170417467e9815eada63bdbdf2":{
        "scriptId":"u35"},
      "2003098ee0234a058a13919dad275e07":{
        "scriptId":"u36"},
      "131dcb64c5b64eaf9727db0ff5da22a6":{
        "scriptId":"u37"},
      "57955a7f69894cfe91133a475b6d8f6f":{
        "scriptId":"u38"},
      "7bebfd875fda4c26adb79875f309dca8":{
        "scriptId":"u39"},
      "8672a055a85f4a3ea48a54377f909e7c":{
        "scriptId":"u40"},
      "4dc0d1b9cfb74e6ea7e30068da017d5b":{
        "scriptId":"u41"},
      "6599a0e13f6b4ea49a3d527489612b2a":{
        "scriptId":"u42"},
      "1087cb033ba644918269a0311bd5ab5c":{
        "scriptId":"u43"},
      "ce0a950f883342d4ab6d1be3cd0d810c":{
        "scriptId":"u44"}}}});