$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1399258299056.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"672dc014d0614fb19eb201a684c619e5",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0dbf299bd5ee4c4c905b6b46b1ca59f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":23},
            "size":{
              "width":371,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"458f1cc8366948859d5e63467926ab18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":23},
                "size":{
                  "width":371,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f39d0132eecf4f1b9734d071553aa4e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":80},
            "size":{
              "width":1174,
              "height":686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f899a66554d4dc183ac559b17709e46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":80},
                "size":{
                  "width":1174,
                  "height":686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0dbf299bd5ee4c4c905b6b46b1ca59f4":{
      "scriptId":"u0"},
    "458f1cc8366948859d5e63467926ab18":{
      "scriptId":"u1"},
    "f39d0132eecf4f1b9734d071553aa4e6":{
      "scriptId":"u2"},
    "3f899a66554d4dc183ac559b17709e46":{
      "scriptId":"u3"}}});