$axure.loadCurrentPage({
  "url":"vs.html",
  "generationDate":new Date(1399955990540.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1f5236ed8994ee684ab54d863bdef63",
    "type":"Axure:Page",
    "name":"VS",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a53a15be62842119ddbed496712e2b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA3A3A3,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFAFAFA},
            "location":{
              "x":214,
              "y":118},
            "size":{
              "width":1086,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03528a16dc04430a03e7e81cf4aa118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA3A3A3,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFAFAFA},
                "location":{
                  "x":214,
                  "y":118},
                "size":{
                  "width":1086,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u0.png"}},
{
          "id":"e8a46a90a6b94d6689f126feec221443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA3A3A3,
              "opacity":1},
            "location":{
              "x":0,
              "y":118},
            "size":{
              "width":215,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8514b00b731343e8a47a131ca3405b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA3A3A3,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":118},
                "size":{
                  "width":215,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u2.png"}},
{
          "id":"65ad805b4bb441569268f01075d02f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA3A3A3,
              "opacity":1},
            "location":{
              "x":0,
              "y":49},
            "size":{
              "width":1300,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE8E8E8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2a86a671c942658f6a6fa5cd5f0167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA3A3A3,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":49},
                "size":{
                  "width":1300,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE8E8E8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u4.png"}},
{
          "id":"b144caac45b64210aa5a385bf506a0da",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"},
{
          "id":"81b80328c86b4a98bfcd68c0a3911983",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":1120,
              "y":61},
            "size":{
              "width":170,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64ce8f50428d4dd09c528f40d41e5435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":1120,
                  "y":61},
                "size":{
                  "width":170,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c9cf5e992624b18b9350c33fd1dc856",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Light', 'Helvetica Light', 'Helvetica'",
            "fontSize":"24px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF717171,
              "opacity":1},
            "location":{
              "x":21,
              "y":67},
            "size":{
              "width":120,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec03c8e2837408da464198df109b10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Light', 'Helvetica Light', 'Helvetica'",
                "fontSize":"24px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF717171,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":67},
                "size":{
                  "width":120,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5c5e909262f492c9487135bda690ef0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":65},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f74e0dd5aa4af7b9ca744a51998aa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":65},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mainscreen/u263.png"}},
{
          "id":"ef05ce4c65294d7caf7dd6769d5c9dc0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":50},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"8c5eca3951a042518d9df2f3d687142c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":80},
            "size":{
              "width":159,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d5394d8ceb4067be90f759ed8bf8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":80},
                "size":{
                  "width":159,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open MakeDecision in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"makedecision.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u261.png"}},
{
          "id":"bd05094d2b934610bef59395beabf862",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":56},
            "size":{
              "width":190,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dbc945fa0f74379975c023bee74b19f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":56},
                "size":{
                  "width":190,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u263.png"}},
{
          "id":"4ff5e395a38d49d18ca382f67fc04d53",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":50},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"556a54db12b9430e8c63388f20ebed91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":62},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff5523ca63ea458691643ec605e05956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":62},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open VS in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u266.png"}},
{
          "id":"e428c66e99fd4eee99bd6b25d6ebeab0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":49},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"8f12ffb727dc4f43bc2149fbc3e0fe85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":757,
              "y":92},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aca2d7d8316e40dfa1efb281b2dea116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":757,
                  "y":92},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67d9f1504cce41059ac614a00fbdf436",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":62},
            "size":{
              "width":465,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b746039406647bb96834a72a8456ab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":62},
                "size":{
                  "width":465,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u271.png"}},
{
          "id":"3a3c549734c743708848d453dcee6fdb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":49},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"dcea736fbc444373a0710c28b9e7806f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD3D4D9,
              "opacity":1},
            "location":{
              "x":360,
              "y":64},
            "size":{
              "width":300,
              "height":39}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1<br> (If length of value of widget This is greater than &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetValueLength",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}}},
{
          "id":"992f1628feb24a55a87a4a363566f36c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":72},
            "size":{
              "width":45,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true},
{
          "id":"47f8a667b1ac47de88851de00c7f6131",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":256,
              "y":69},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"27687533ae8a46c8b7ff1f3e0012e4e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":25,
              "y":129},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bdf7bcb5909494d8dc6cadc67262f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":129},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca8dfdc0558470f813d071fe0ea6c97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":156},
            "size":{
              "width":215,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb03a88ed7d148ef9415b31fdb6bae82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":156},
                "size":{
                  "width":215,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u279.png"}},
{
          "id":"6f49d9550b37410d9c696d30be7ad6e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":210},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3909f602e24f44459b0cd2c2713acbda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":210},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"c92eb01a681e473d94c2490e8f4587cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":211},
            "size":{
              "width":80,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94eef80d1fa645b3874196491021a4db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":211},
                "size":{
                  "width":80,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d40263942c946fda6299f83be75683b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":246},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d04571ea5aa41de941f667953c512a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":246},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"cd7f2fa4e7d340ffa899a8db47e3f705",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":247},
            "size":{
              "width":99,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"461616c94bcb4664b860c58ffc61b383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":247},
                "size":{
                  "width":99,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"586567124bbe4b64b5595c17f6b1a2fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":275},
            "size":{
              "width":213,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE3E5EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u289_line.png"}},
{
          "id":"8edf2a138d354e4d8511f589a52f6df0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":25,
              "y":297},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5c897ecc44c437aacf0788156737c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":297},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b236d3c4a7a44080a3522fa491e9cb5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":333},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576fd2f3cedc41e686b4a9019953e40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":333},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"cba63bbeb5834c80bb6a79ec12e5cecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":334},
            "size":{
              "width":78,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e848334a0b4040933957fb0fe119b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":334},
                "size":{
                  "width":78,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb63ab58e34f475c9f2751f17479fa8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":369},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e7a44eec0514f299ef8e170896836c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":369},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"f609ccf2fa934adf94de7552010f7b0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":370},
            "size":{
              "width":133,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da7e156de6f46b7a41c8ab8bc871ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":370},
                "size":{
                  "width":133,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aaf0b3779db49b69754ecf4a86d4a75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":404},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e159dc5ea3174d0dae9830aab4ab762c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":404},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"ca6ab4fdbbfe4ecd9bb254ede3192f08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":405},
            "size":{
              "width":89,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"741a54d08cca44d29cf523537f5c4e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":405},
                "size":{
                  "width":89,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96c2ff5c78144d2e80d7a315eca16f36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":440},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e92e6b9cca6243de9245a364347a0d54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":440},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"6c4327ff2bf6400993f241c147af24fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":440},
            "size":{
              "width":145,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b54e5f1af48437c84bed430c9e8b0cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":440},
                "size":{
                  "width":145,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9295b5b5435b4575919d75a0165da637",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":213,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE3E5EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u289_line.png"}},
{
          "id":"e7b8537b8faa41a882b1cb9508d669cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":25,
              "y":490},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b181368298484fa1160167001df6c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":490},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aec112f5429458cbeff4dfcbad5836b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":526},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3dfe600d6a845479f6354d62d391930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":526},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"93346d62b60e48b49d56375f6ca3fef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":527},
            "size":{
              "width":127,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb895bdb7e804127b5f5533b84403589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":527},
                "size":{
                  "width":127,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"269e060b7e1146e392bf62af3a880bd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":562},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5fbbfe1d83d44d5a7610fc94f699eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":562},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"a4b4ba7aa74047378ff9d35f8a43797c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":563},
            "size":{
              "width":88,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5acef05d41584a92987d59438560f813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":563},
                "size":{
                  "width":88,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1333a5005ef04fc8b2bc40d3738f85ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":598},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320f53444a104dbd9beb19a5a2db58d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":598},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"cdfa9b54415a4205a517a9599089c922",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":599},
            "size":{
              "width":126,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82c128d6ea8b4d5cbcab895d508df5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":599},
                "size":{
                  "width":126,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d643ad24494e40a6be4cdd1da3022764",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":634},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e513e3a0744fcdbdf222785b8ae7cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":634},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"1f70b7374de641d6b62d5090bad1bf20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":634},
            "size":{
              "width":96,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34467b54178e4a1b807ebcbad6b909b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":634},
                "size":{
                  "width":96,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a7928c15efb4a47b24eced486dd5544",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":670},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb016ddf46a4df88a060b6eb440d6a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":670},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u281.png"}},
{
          "id":"f2d9d7f565f54078bdc3fffff6bbc40c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":50,
              "y":670},
            "size":{
              "width":95,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7950de886d9418285cd536770b1a835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6F6F6F,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":670},
                "size":{
                  "width":95,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"190f1886086d496987c002070a35064a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":211},
            "size":{
              "width":840,
              "height":316}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1efe33b167d474da1d5a744715bd2cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":211},
                "size":{
                  "width":840,
                  "height":316}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vs/u108.png"}},
{
          "id":"1a5b1b0920bd4702b09b7975d26ae7a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":726,
              "y":148},
            "size":{
              "width":38,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b412e5a124d4537bfcff99fe0a2415e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":726,
                  "y":148},
                "size":{
                  "width":38,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "size":{
                "width":1301,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF294590},
                  "size":{
                    "width":1301,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"f1138e4bb64a4b03a9c6dc5d544ec919",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"888ba27679964561b0d5cb2a0ef3c9b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u27.png"}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b79d47f0fac44b12b3883c52e1e972ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4B67AE},
              "location":{
                "x":203,
                "y":1},
              "size":{
                "width":73,
                "height":40},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73173e2d2f9942cc95bb9e59f7e1d295",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4B67AE},
                  "location":{
                    "x":203,
                    "y":1},
                  "size":{
                    "width":73,
                    "height":40},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u31.png"}},
{
            "id":"a19273aad5e84f14b1fa81e5785797c6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":202,
                "y":39},
              "size":{
                "width":74,
                "height":10}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaaab34ad5a9472aa24182c8c888f172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":202,
                    "y":39},
                  "size":{
                    "width":74,
                    "height":10}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u33.png"}},
{
            "id":"59fe3b170417467e9815eada63bdbdf2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":221,
                "y":17},
              "size":{
                "width":37,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2003098ee0234a058a13919dad275e07",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":221,
                    "y":17},
                  "size":{
                    "width":37,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"131dcb64c5b64eaf9727db0ff5da22a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":304,
                "y":17},
              "size":{
                "width":43,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57955a7f69894cfe91133a475b6d8f6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":304,
                    "y":17},
                  "size":{
                    "width":43,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bebfd875fda4c26adb79875f309dca8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":393,
                "y":17},
              "size":{
                "width":35,
                "height":1}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8672a055a85f4a3ea48a54377f909e7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":393,
                    "y":17},
                  "size":{
                    "width":35,
                    "height":1}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ViewHistoryScore in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"viewhistoryscore.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4dc0d1b9cfb74e6ea7e30068da017d5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":474,
                "y":17},
              "size":{
                "width":54,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6599a0e13f6b4ea49a3d527489612b2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":17},
                  "size":{
                    "width":54,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1087cb033ba644918269a0311bd5ab5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"9px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":431,
                "y":12},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce0a950f883342d4ab6d1be3cd0d810c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"9px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":431,
                    "y":12},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "4a53a15be62842119ddbed496712e2b7":{
      "scriptId":"u0"},
    "f03528a16dc04430a03e7e81cf4aa118":{
      "scriptId":"u1"},
    "e8a46a90a6b94d6689f126feec221443":{
      "scriptId":"u2"},
    "8514b00b731343e8a47a131ca3405b16":{
      "scriptId":"u3"},
    "65ad805b4bb441569268f01075d02f06":{
      "scriptId":"u4"},
    "0a2a86a671c942658f6a6fa5cd5f0167":{
      "scriptId":"u5"},
    "b144caac45b64210aa5a385bf506a0da":{
      "scriptId":"u6",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u7"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u8"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u9"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u10"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u11"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u12"},
      "f1138e4bb64a4b03a9c6dc5d544ec919":{
        "scriptId":"u13"},
      "888ba27679964561b0d5cb2a0ef3c9b2":{
        "scriptId":"u14"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u15"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u16"},
      "b79d47f0fac44b12b3883c52e1e972ca":{
        "scriptId":"u17"},
      "73173e2d2f9942cc95bb9e59f7e1d295":{
        "scriptId":"u18"},
      "a19273aad5e84f14b1fa81e5785797c6":{
        "scriptId":"u19"},
      "eaaab34ad5a9472aa24182c8c888f172":{
        "scriptId":"u20"},
      "59fe3b170417467e9815eada63bdbdf2":{
        "scriptId":"u21"},
      "2003098ee0234a058a13919dad275e07":{
        "scriptId":"u22"},
      "131dcb64c5b64eaf9727db0ff5da22a6":{
        "scriptId":"u23"},
      "57955a7f69894cfe91133a475b6d8f6f":{
        "scriptId":"u24"},
      "7bebfd875fda4c26adb79875f309dca8":{
        "scriptId":"u25"},
      "8672a055a85f4a3ea48a54377f909e7c":{
        "scriptId":"u26"},
      "4dc0d1b9cfb74e6ea7e30068da017d5b":{
        "scriptId":"u27"},
      "6599a0e13f6b4ea49a3d527489612b2a":{
        "scriptId":"u28"},
      "1087cb033ba644918269a0311bd5ab5c":{
        "scriptId":"u29"},
      "ce0a950f883342d4ab6d1be3cd0d810c":{
        "scriptId":"u30"}},
    "81b80328c86b4a98bfcd68c0a3911983":{
      "scriptId":"u31"},
    "64ce8f50428d4dd09c528f40d41e5435":{
      "scriptId":"u32"},
    "0c9cf5e992624b18b9350c33fd1dc856":{
      "scriptId":"u33"},
    "0ec03c8e2837408da464198df109b10e":{
      "scriptId":"u34"},
    "e5c5e909262f492c9487135bda690ef0":{
      "scriptId":"u35"},
    "54f74e0dd5aa4af7b9ca744a51998aa1":{
      "scriptId":"u36"},
    "ef05ce4c65294d7caf7dd6769d5c9dc0":{
      "scriptId":"u37"},
    "8c5eca3951a042518d9df2f3d687142c":{
      "scriptId":"u38"},
    "e2d5394d8ceb4067be90f759ed8bf8f0":{
      "scriptId":"u39"},
    "bd05094d2b934610bef59395beabf862":{
      "scriptId":"u40"},
    "9dbc945fa0f74379975c023bee74b19f":{
      "scriptId":"u41"},
    "4ff5e395a38d49d18ca382f67fc04d53":{
      "scriptId":"u42"},
    "556a54db12b9430e8c63388f20ebed91":{
      "scriptId":"u43"},
    "ff5523ca63ea458691643ec605e05956":{
      "scriptId":"u44"},
    "e428c66e99fd4eee99bd6b25d6ebeab0":{
      "scriptId":"u45"},
    "8f12ffb727dc4f43bc2149fbc3e0fe85":{
      "scriptId":"u46"},
    "aca2d7d8316e40dfa1efb281b2dea116":{
      "scriptId":"u47"},
    "67d9f1504cce41059ac614a00fbdf436":{
      "scriptId":"u48"},
    "5b746039406647bb96834a72a8456ab0":{
      "scriptId":"u49"},
    "3a3c549734c743708848d453dcee6fdb":{
      "scriptId":"u50"},
    "dcea736fbc444373a0710c28b9e7806f":{
      "scriptId":"u51"},
    "992f1628feb24a55a87a4a363566f36c":{
      "scriptId":"u52"},
    "47f8a667b1ac47de88851de00c7f6131":{
      "scriptId":"u53"},
    "27687533ae8a46c8b7ff1f3e0012e4e0":{
      "scriptId":"u54"},
    "3bdf7bcb5909494d8dc6cadc67262f8b":{
      "scriptId":"u55"},
    "8ca8dfdc0558470f813d071fe0ea6c97":{
      "scriptId":"u56"},
    "fb03a88ed7d148ef9415b31fdb6bae82":{
      "scriptId":"u57"},
    "6f49d9550b37410d9c696d30be7ad6e7":{
      "scriptId":"u58"},
    "3909f602e24f44459b0cd2c2713acbda":{
      "scriptId":"u59"},
    "c92eb01a681e473d94c2490e8f4587cc":{
      "scriptId":"u60"},
    "94eef80d1fa645b3874196491021a4db":{
      "scriptId":"u61"},
    "0d40263942c946fda6299f83be75683b":{
      "scriptId":"u62"},
    "9d04571ea5aa41de941f667953c512a5":{
      "scriptId":"u63"},
    "cd7f2fa4e7d340ffa899a8db47e3f705":{
      "scriptId":"u64"},
    "461616c94bcb4664b860c58ffc61b383":{
      "scriptId":"u65"},
    "586567124bbe4b64b5595c17f6b1a2fd":{
      "scriptId":"u66"},
    "8edf2a138d354e4d8511f589a52f6df0":{
      "scriptId":"u67"},
    "b5c897ecc44c437aacf0788156737c06":{
      "scriptId":"u68"},
    "b236d3c4a7a44080a3522fa491e9cb5d":{
      "scriptId":"u69"},
    "576fd2f3cedc41e686b4a9019953e40d":{
      "scriptId":"u70"},
    "cba63bbeb5834c80bb6a79ec12e5cecf":{
      "scriptId":"u71"},
    "d3e848334a0b4040933957fb0fe119b5":{
      "scriptId":"u72"},
    "fb63ab58e34f475c9f2751f17479fa8c":{
      "scriptId":"u73"},
    "2e7a44eec0514f299ef8e170896836c8":{
      "scriptId":"u74"},
    "f609ccf2fa934adf94de7552010f7b0a":{
      "scriptId":"u75"},
    "9da7e156de6f46b7a41c8ab8bc871ef2":{
      "scriptId":"u76"},
    "5aaf0b3779db49b69754ecf4a86d4a75":{
      "scriptId":"u77"},
    "e159dc5ea3174d0dae9830aab4ab762c":{
      "scriptId":"u78"},
    "ca6ab4fdbbfe4ecd9bb254ede3192f08":{
      "scriptId":"u79"},
    "741a54d08cca44d29cf523537f5c4e2c":{
      "scriptId":"u80"},
    "96c2ff5c78144d2e80d7a315eca16f36":{
      "scriptId":"u81"},
    "e92e6b9cca6243de9245a364347a0d54":{
      "scriptId":"u82"},
    "6c4327ff2bf6400993f241c147af24fc":{
      "scriptId":"u83"},
    "2b54e5f1af48437c84bed430c9e8b0cf":{
      "scriptId":"u84"},
    "9295b5b5435b4575919d75a0165da637":{
      "scriptId":"u85"},
    "e7b8537b8faa41a882b1cb9508d669cc":{
      "scriptId":"u86"},
    "36b181368298484fa1160167001df6c7":{
      "scriptId":"u87"},
    "8aec112f5429458cbeff4dfcbad5836b":{
      "scriptId":"u88"},
    "f3dfe600d6a845479f6354d62d391930":{
      "scriptId":"u89"},
    "93346d62b60e48b49d56375f6ca3fef7":{
      "scriptId":"u90"},
    "bb895bdb7e804127b5f5533b84403589":{
      "scriptId":"u91"},
    "269e060b7e1146e392bf62af3a880bd8":{
      "scriptId":"u92"},
    "e5fbbfe1d83d44d5a7610fc94f699eb8":{
      "scriptId":"u93"},
    "a4b4ba7aa74047378ff9d35f8a43797c":{
      "scriptId":"u94"},
    "5acef05d41584a92987d59438560f813":{
      "scriptId":"u95"},
    "1333a5005ef04fc8b2bc40d3738f85ca":{
      "scriptId":"u96"},
    "320f53444a104dbd9beb19a5a2db58d0":{
      "scriptId":"u97"},
    "cdfa9b54415a4205a517a9599089c922":{
      "scriptId":"u98"},
    "82c128d6ea8b4d5cbcab895d508df5f7":{
      "scriptId":"u99"},
    "d643ad24494e40a6be4cdd1da3022764":{
      "scriptId":"u100"},
    "44e513e3a0744fcdbdf222785b8ae7cd":{
      "scriptId":"u101"},
    "1f70b7374de641d6b62d5090bad1bf20":{
      "scriptId":"u102"},
    "34467b54178e4a1b807ebcbad6b909b1":{
      "scriptId":"u103"},
    "8a7928c15efb4a47b24eced486dd5544":{
      "scriptId":"u104"},
    "cbb016ddf46a4df88a060b6eb440d6a0":{
      "scriptId":"u105"},
    "f2d9d7f565f54078bdc3fffff6bbc40c":{
      "scriptId":"u106"},
    "d7950de886d9418285cd536770b1a835":{
      "scriptId":"u107"},
    "190f1886086d496987c002070a35064a":{
      "scriptId":"u108"},
    "e1efe33b167d474da1d5a744715bd2cd":{
      "scriptId":"u109"},
    "1a5b1b0920bd4702b09b7975d26ae7a9":{
      "scriptId":"u110"},
    "4b412e5a124d4537bfcff99fe0a2415e":{
      "scriptId":"u111"}}});