$axure.loadCurrentPage({
  "url":"vs.html",
  "generationDate":new Date(1398317599311.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1f5236ed8994ee684ab54d863bdef63",
    "type":"Axure:Page",
    "name":"VS",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23a3ae9ffa774a09bf8e430ea7c5b03d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"},
{
          "id":"2d055ce97e6c4099b31f8da113d00bc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":1360,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"008408ab09e3411a8b9a91b45e41e82b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":1360,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u9.png"}},
{
          "id":"86338a25daa84e4da15bd049b4ec4064",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0874232c01494895a0a110b1970ee815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":60},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d022f2518e0475bace2b4783163d12f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":55},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"8b7161944b1745cab72cfa7775d20bf3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":55},
            "size":{
              "width":580,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1<br> (If length of value of widget This is greater than &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetValueLength",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}}},
{
          "id":"e800bdf6557848f7b0e206e16ac1cc54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":55},
            "size":{
              "width":200,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ca1bc385d7d4c6ab9b5e30cca58b335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":55},
                "size":{
                  "width":200,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0866e3db4794cfc8182ff3721f53e92",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":90},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d64ac80704c24a04be1f38c909e7116f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":180,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c42c13f22e940d09e3aaa69148c5b74",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":115}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f80ed28e3ba450a8decf199c487fa44",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf0eb0468cfb4722ad643dd379fa17c4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u20.png"}},
{
                  "id":"0ff214aebe6e4e9795d078bfda805925",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebaa389374c34c5d9d4b985f475e32ac",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"ba49750f61b54bee8dff18c0162389c3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f78684f638df41799031831139ff9c77",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":65},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"3a7e25d010e942b1891cd1c3eb5c3feb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eca9f912f6394448b8f3844a539eb3b1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":90},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u26.png"}}]}]},
{
          "id":"6de524ab1acb48a189306f533cd63db6",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":265},
            "size":{
              "width":180,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5713212565104823bbf41ce763fe2c08",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":140}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70bc132d8df644628a21c4b5204fae21",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eaf9c6b8415d4d3c9279e3f1a2fe874f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u20.png"}},
{
                  "id":"af0a011dd6204bc59ded68580a358116",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b3c0f21c95e47c0980117aba126965a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"f54b7e858b924ffeb5268d1219b80a93",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbebcf6187674260a2bf6fff68ab6a95",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":65},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"57961cc13b7144048bb5a323dce5bb2d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d69177d38c44a21aab2c9baad40bc9b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":90},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"7e985d67090f4f75b6bb681abaa4c4e1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66af40ff3bda4806822acefa2de7524f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u26.png"}}]}]},
{
          "id":"3d4954247a1447fe88e038f77445e8d1",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":180,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605f5be551e54091ad32720f961a7448",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":165}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c879c564cb6c4a77aa1a502a68adcce8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa8351859132456f9432df51f7c73e87",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u20.png"}},
{
                  "id":"adaf6318fc1a4d469b12ed83d42ed436",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da531821b30f44dfa5bda21bd07c09f9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"b58591f44d0d4017bc67e051f6111b48",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":65},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7aae0280c5894bf1afb6208566f9b2b7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":65},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"ae34794f8e984a9f9b98f214f617086d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8562bf982dfe403092cc31624b295b94",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":90},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"59bd7748d8c248ed908f7d5f71ed7daa",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d9b516c898044619524d81df3b3de3b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u22.png"}},
{
                  "id":"4beed364afcc457fa033d6b893ce88a6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":180,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2c66a465dfe4d5288a9a493322e58f6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":140},
                        "size":{
                          "width":180,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/report/u26.png"}}]}]},
{
          "id":"91fc9bd6f9634b6f91c8fd849f85caf8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1115,
              "y":136}},
          "adaptiveStyles":{
},
          "masterId":"bdf69ede011043dabc732bbbc846e78d"},
{
          "id":"190f1886086d496987c002070a35064a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":214},
            "size":{
              "width":840,
              "height":316}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1efe33b167d474da1d5a744715bd2cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":214},
                "size":{
                  "width":840,
                  "height":316}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vs/u74.png"}},
{
          "id":"1a5b1b0920bd4702b09b7975d26ae7a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":612,
              "y":158},
            "size":{
              "width":38,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b412e5a124d4537bfcff99fe0a2415e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":612,
                  "y":158},
                "size":{
                  "width":38,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"343f45adb7ab4acfbf3e08d2a1aeb2b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":580},
            "size":{
              "width":124,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e80baf24d2042feb9dc3c444b77b94b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":580},
                "size":{
                  "width":124,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31f5d61f763a446ba72902b6d486d530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":220,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8736e86f599b499d8e871dccf887d1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":220,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u152.png"}},
{
          "id":"7176f55fffc945b6901bea717897373f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF993300},
            "location":{
              "x":300,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ff27d9b53d5488b86e83a77e9d6235c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF993300},
                "location":{
                  "x":300,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u174.png"}},
{
          "id":"9853010f20414918a22db8a42bd2f80c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b2cc86f86e4d77acd54930701690e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"c1db499c5d4c4a64a2a41fe8191d4805",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb89739f9304d57abb7f5dd73564ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"27fa37021bb64ec0b3fff91a682be8f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c87e3d3d8d477f8519692d69cb58f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"66c068c2c2694defba77f1f5306ca910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8177f4a6d14806ace9121017522e0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"7cf1cc9694ea4109bd0b480d7a1ebff1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879ab175e7bf42f1a36919d04fc524c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"1d54439de38e4874a6c91cc505673ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"846229a8c9754d00920539dcd52fd6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"cd3ce6881c2d43d0a73f45b4c29725f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1119c6cd24e489ca904f7d76bff49bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}},
{
          "id":"30caa3af601e47b1b76fc24ca834fc09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":605},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ae9504326e4e25a30776ce5a2328d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":605},
                "size":{
                  "width":70,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u132.png"}}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "size":{
                "width":1370,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "size":{
                    "width":1370,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1236,
                "y":12},
              "size":{
                "width":113,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1236,
                    "y":12},
                  "size":{
                    "width":113,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "location":{
                "x":1150,
                "y":9},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "location":{
                "x":1020,
                "y":9},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":20,
                "y":12},
              "size":{
                "width":72,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":20,
                    "y":12},
                  "size":{
                    "width":72,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "bdf69ede011043dabc732bbbc846e78d":{
      "packageId":"bdf69ede011043dabc732bbbc846e78d",
      "type":"Axure:Master",
      "name":"UserMainMessager",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"65ac351e89de4a88b37a22b7ff1e8d79",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":250,
                "height":700},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"91ab81e1251746a3977434a3cf200e74",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":250,
                    "height":700},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u112.png"}},
{
            "id":"1a644aaf30634c15b422f9147f5faf56",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F,
                "opacity":1},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":70,
                "height":40},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7bd26c63b2504f1ba7dfd47979acae23",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":70,
                    "height":40},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u114.png"}},
{
            "id":"146ddd9ae00a4e86b32fdc1de73eb711",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBAC4AF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFECF0E7},
              "location":{
                "x":80,
                "y":10},
              "size":{
                "width":84,
                "height":40},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9098280e93f64e0eae204be4ba9840a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBAC4AF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFECF0E7},
                  "location":{
                    "x":80,
                    "y":10},
                  "size":{
                    "width":84,
                    "height":40},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u116.png"}},
{
            "id":"55fcf63c22de462e8b9734d851fab098",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":8},
              "size":{
                "width":75,
                "height":10},
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/mainscreen/u118_line.png"}},
{
            "id":"661ab10d52d84c7aafee28e204b26818",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":24,
                "y":80},
              "size":{
                "width":97,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7454751550934e5e8208ee63d35bbb57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":24,
                    "y":80},
                  "size":{
                    "width":97,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3527fa3965ee4d8d886915c5cfc6fc76",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":124,
                "y":76},
              "size":{
                "width":84,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"534030fb3f814a3a97858fe6d384f413",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":15,
                "y":120},
              "size":{
                "width":220,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/mainscreen/u122_line.png"}},
{
            "id":"76ecba4166aa44d1bdc083e4a03a2354",
            "label":"",
            "type":"checkbox",
            "styleType":"checkbox",
            "visible":true,
            "style":{
              "location":{
                "x":24,
                "y":160},
              "size":{
                "width":211,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed093c4cf3464c2782ae3f282f3ad911",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":24,
                    "y":160},
                  "size":{
                    "width":211,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"d09a5c8c047d4615bd5eecde66237171",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":15,
                "y":190},
              "size":{
                "width":220,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/mainscreen/u122_line.png"}},
{
            "id":"b16182edb7aa4fabaad29117c960e62f",
            "label":"",
            "type":"checkbox",
            "styleType":"checkbox",
            "visible":true,
            "style":{
              "location":{
                "x":24,
                "y":219},
              "size":{
                "width":211,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9154190e008f465087a4b8ca6c6dde91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":24,
                    "y":219},
                  "size":{
                    "width":211,
                    "height":15}},
                "adaptiveStyles":{
}}]},
{
            "id":"5f6f8a0b0f2443bf9737adc70ff36e09",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":15,
                "y":249},
              "size":{
                "width":220,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/mainscreen/u122_line.png"}},
{
            "id":"c0794abf6b2d4f38bd5eff2469bab1c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBAC4AF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFECF0E7},
              "location":{
                "x":164,
                "y":10},
              "size":{
                "width":86,
                "height":40},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"615b8a91a8d2495fb3ca0936ca7b54e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBAC4AF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFECF0E7},
                  "location":{
                    "x":164,
                    "y":10},
                  "size":{
                    "width":86,
                    "height":40},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u129.png"}}]}}},
  "objectPaths":{
    "23a3ae9ffa774a09bf8e430ea7c5b03d":{
      "scriptId":"u0",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u1"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u2"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u3"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u4"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u5"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u6"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u7"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u8"}},
    "2d055ce97e6c4099b31f8da113d00bc5":{
      "scriptId":"u9"},
    "008408ab09e3411a8b9a91b45e41e82b":{
      "scriptId":"u10"},
    "86338a25daa84e4da15bd049b4ec4064":{
      "scriptId":"u11"},
    "0874232c01494895a0a110b1970ee815":{
      "scriptId":"u12"},
    "8d022f2518e0475bace2b4783163d12f":{
      "scriptId":"u13"},
    "8b7161944b1745cab72cfa7775d20bf3":{
      "scriptId":"u14"},
    "e800bdf6557848f7b0e206e16ac1cc54":{
      "scriptId":"u15"},
    "7ca1bc385d7d4c6ab9b5e30cca58b335":{
      "scriptId":"u16"},
    "f0866e3db4794cfc8182ff3721f53e92":{
      "scriptId":"u17"},
    "d64ac80704c24a04be1f38c909e7116f":{
      "scriptId":"u18"},
    "2c42c13f22e940d09e3aaa69148c5b74":{
      "scriptId":"u19"},
    "8f80ed28e3ba450a8decf199c487fa44":{
      "scriptId":"u20"},
    "bf0eb0468cfb4722ad643dd379fa17c4":{
      "scriptId":"u21"},
    "0ff214aebe6e4e9795d078bfda805925":{
      "scriptId":"u22"},
    "ebaa389374c34c5d9d4b985f475e32ac":{
      "scriptId":"u23"},
    "ba49750f61b54bee8dff18c0162389c3":{
      "scriptId":"u24"},
    "f78684f638df41799031831139ff9c77":{
      "scriptId":"u25"},
    "3a7e25d010e942b1891cd1c3eb5c3feb":{
      "scriptId":"u26"},
    "eca9f912f6394448b8f3844a539eb3b1":{
      "scriptId":"u27"},
    "6de524ab1acb48a189306f533cd63db6":{
      "scriptId":"u28"},
    "5713212565104823bbf41ce763fe2c08":{
      "scriptId":"u29"},
    "70bc132d8df644628a21c4b5204fae21":{
      "scriptId":"u30"},
    "eaf9c6b8415d4d3c9279e3f1a2fe874f":{
      "scriptId":"u31"},
    "af0a011dd6204bc59ded68580a358116":{
      "scriptId":"u32"},
    "0b3c0f21c95e47c0980117aba126965a":{
      "scriptId":"u33"},
    "f54b7e858b924ffeb5268d1219b80a93":{
      "scriptId":"u34"},
    "fbebcf6187674260a2bf6fff68ab6a95":{
      "scriptId":"u35"},
    "57961cc13b7144048bb5a323dce5bb2d":{
      "scriptId":"u36"},
    "1d69177d38c44a21aab2c9baad40bc9b":{
      "scriptId":"u37"},
    "7e985d67090f4f75b6bb681abaa4c4e1":{
      "scriptId":"u38"},
    "66af40ff3bda4806822acefa2de7524f":{
      "scriptId":"u39"},
    "3d4954247a1447fe88e038f77445e8d1":{
      "scriptId":"u40"},
    "605f5be551e54091ad32720f961a7448":{
      "scriptId":"u41"},
    "c879c564cb6c4a77aa1a502a68adcce8":{
      "scriptId":"u42"},
    "aa8351859132456f9432df51f7c73e87":{
      "scriptId":"u43"},
    "adaf6318fc1a4d469b12ed83d42ed436":{
      "scriptId":"u44"},
    "da531821b30f44dfa5bda21bd07c09f9":{
      "scriptId":"u45"},
    "b58591f44d0d4017bc67e051f6111b48":{
      "scriptId":"u46"},
    "7aae0280c5894bf1afb6208566f9b2b7":{
      "scriptId":"u47"},
    "ae34794f8e984a9f9b98f214f617086d":{
      "scriptId":"u48"},
    "8562bf982dfe403092cc31624b295b94":{
      "scriptId":"u49"},
    "59bd7748d8c248ed908f7d5f71ed7daa":{
      "scriptId":"u50"},
    "8d9b516c898044619524d81df3b3de3b":{
      "scriptId":"u51"},
    "4beed364afcc457fa033d6b893ce88a6":{
      "scriptId":"u52"},
    "f2c66a465dfe4d5288a9a493322e58f6":{
      "scriptId":"u53"},
    "91fc9bd6f9634b6f91c8fd849f85caf8":{
      "scriptId":"u54",
      "65ac351e89de4a88b37a22b7ff1e8d79":{
        "scriptId":"u55"},
      "91ab81e1251746a3977434a3cf200e74":{
        "scriptId":"u56"},
      "1a644aaf30634c15b422f9147f5faf56":{
        "scriptId":"u57"},
      "7bd26c63b2504f1ba7dfd47979acae23":{
        "scriptId":"u58"},
      "146ddd9ae00a4e86b32fdc1de73eb711":{
        "scriptId":"u59"},
      "9098280e93f64e0eae204be4ba9840a7":{
        "scriptId":"u60"},
      "55fcf63c22de462e8b9734d851fab098":{
        "scriptId":"u61"},
      "661ab10d52d84c7aafee28e204b26818":{
        "scriptId":"u62"},
      "7454751550934e5e8208ee63d35bbb57":{
        "scriptId":"u63"},
      "3527fa3965ee4d8d886915c5cfc6fc76":{
        "scriptId":"u64"},
      "534030fb3f814a3a97858fe6d384f413":{
        "scriptId":"u65"},
      "76ecba4166aa44d1bdc083e4a03a2354":{
        "scriptId":"u66"},
      "ed093c4cf3464c2782ae3f282f3ad911":{
        "scriptId":"u67"},
      "d09a5c8c047d4615bd5eecde66237171":{
        "scriptId":"u68"},
      "b16182edb7aa4fabaad29117c960e62f":{
        "scriptId":"u69"},
      "9154190e008f465087a4b8ca6c6dde91":{
        "scriptId":"u70"},
      "5f6f8a0b0f2443bf9737adc70ff36e09":{
        "scriptId":"u71"},
      "c0794abf6b2d4f38bd5eff2469bab1c4":{
        "scriptId":"u72"},
      "615b8a91a8d2495fb3ca0936ca7b54e2":{
        "scriptId":"u73"}},
    "190f1886086d496987c002070a35064a":{
      "scriptId":"u74"},
    "e1efe33b167d474da1d5a744715bd2cd":{
      "scriptId":"u75"},
    "1a5b1b0920bd4702b09b7975d26ae7a9":{
      "scriptId":"u76"},
    "4b412e5a124d4537bfcff99fe0a2415e":{
      "scriptId":"u77"},
    "343f45adb7ab4acfbf3e08d2a1aeb2b0":{
      "scriptId":"u78"},
    "3e80baf24d2042feb9dc3c444b77b94b":{
      "scriptId":"u79"},
    "31f5d61f763a446ba72902b6d486d530":{
      "scriptId":"u80"},
    "8736e86f599b499d8e871dccf887d1e3":{
      "scriptId":"u81"},
    "7176f55fffc945b6901bea717897373f":{
      "scriptId":"u82"},
    "8ff27d9b53d5488b86e83a77e9d6235c":{
      "scriptId":"u83"},
    "9853010f20414918a22db8a42bd2f80c":{
      "scriptId":"u84"},
    "90b2cc86f86e4d77acd54930701690e1":{
      "scriptId":"u85"},
    "c1db499c5d4c4a64a2a41fe8191d4805":{
      "scriptId":"u86"},
    "cfb89739f9304d57abb7f5dd73564ab2":{
      "scriptId":"u87"},
    "27fa37021bb64ec0b3fff91a682be8f9":{
      "scriptId":"u88"},
    "29c87e3d3d8d477f8519692d69cb58f3":{
      "scriptId":"u89"},
    "66c068c2c2694defba77f1f5306ca910":{
      "scriptId":"u90"},
    "ac8177f4a6d14806ace9121017522e0b":{
      "scriptId":"u91"},
    "7cf1cc9694ea4109bd0b480d7a1ebff1":{
      "scriptId":"u92"},
    "879ab175e7bf42f1a36919d04fc524c7":{
      "scriptId":"u93"},
    "1d54439de38e4874a6c91cc505673ace":{
      "scriptId":"u94"},
    "846229a8c9754d00920539dcd52fd6f9":{
      "scriptId":"u95"},
    "cd3ce6881c2d43d0a73f45b4c29725f7":{
      "scriptId":"u96"},
    "d1119c6cd24e489ca904f7d76bff49bf":{
      "scriptId":"u97"},
    "30caa3af601e47b1b76fc24ca834fc09":{
      "scriptId":"u98"},
    "39ae9504326e4e25a30776ce5a2328d9":{
      "scriptId":"u99"}}});