$axure.loadCurrentPage({
  "url":"seminarmanagement_1.html",
  "generationDate":new Date(1400493979781.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ff1933a9825f46d8a584a2ab2c0d0b50",
    "type":"Axure:Page",
    "name":"SeminarManagement",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"907426e979344c989711c236eed55c1d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":436},
            "size":{
              "width":600,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c95f86756104ea39807e652a29d2b58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75f280473964408189b88585298da852",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"cbc7c21ccabd4770bcc7e0b7f5ef4fba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54896dc1a4454634ac9cb13dd1e9a025",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"a715fd4ada9f4b2da14511ab1409ba27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a880a44ff69c46f9bf2eb12889897339",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"08797d40db5349bbbc72d618d53fb205",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"422cffa5dc87417191dcb088a8477435",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"8490eb82861d479bb2fb15010bfe4ba5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bef918f9625643199a1df3716b2edf00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"614faad469f64774a979917d4d1f4c29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"740e52dbc92c47f1893af449f3297672",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"05f321e6dc434582af279d1bdafccc21",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3fc4939b84004269a743a3be95d99039",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"654dd0be9b68413595897709bf94bace",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0658abad21b246f9933473acf4fffc56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"5fb570b531d64d9988cfb9ffe3a6540c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8309edd668bf4719834b54caaef1d271",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"9320c2c122774e0e912baccdae2a7227",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef72075f51b947b5b5371b5854aaed7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"0ba660e8465e4bf0a5dee07d0eb7c41b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a2835101dfe44e58bf154990c895518",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"eb8b888d23af4951aafd91a7be01d63b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2794ea5fa8364ed4a29de72e05d5f5ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"e97d302862384e7787253a991f2e1bd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49bb2e08f8f34a56adebf5d7f621de95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u1.png"}},
{
              "id":"c68e641e11ea4d0280f9509210a329d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b21d23a4c0ae45d08d137a6a3011318d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u19.png"}},
{
              "id":"074910347618419bb4f247a02d77cff8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9b704a4d8af4744b9e70e21bda13e55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u37.png"}},
{
              "id":"c8db67541e504e46961f4d1a7d0d93b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a858d0ad56f463d8d4f94bd81ffc0c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u17.png"}},
{
              "id":"587c03ba440f43338cbc63312a45e6cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5fa829a240f42f8afb6daae66a1e294",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u35.png"}},
{
              "id":"d4ea03eba8394b8dbb6d27e2eb76f144",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a21894adfe2849f5868cd97f14fa06e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/seminarmanagement/u53.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "907426e979344c989711c236eed55c1d":{
      "scriptId":"u0"},
    "0c95f86756104ea39807e652a29d2b58":{
      "scriptId":"u1"},
    "75f280473964408189b88585298da852":{
      "scriptId":"u2"},
    "08797d40db5349bbbc72d618d53fb205":{
      "scriptId":"u3"},
    "422cffa5dc87417191dcb088a8477435":{
      "scriptId":"u4"},
    "05f321e6dc434582af279d1bdafccc21":{
      "scriptId":"u5"},
    "3fc4939b84004269a743a3be95d99039":{
      "scriptId":"u6"},
    "9320c2c122774e0e912baccdae2a7227":{
      "scriptId":"u7"},
    "ef72075f51b947b5b5371b5854aaed7e":{
      "scriptId":"u8"},
    "e97d302862384e7787253a991f2e1bd4":{
      "scriptId":"u9"},
    "49bb2e08f8f34a56adebf5d7f621de95":{
      "scriptId":"u10"},
    "c8db67541e504e46961f4d1a7d0d93b1":{
      "scriptId":"u11"},
    "8a858d0ad56f463d8d4f94bd81ffc0c3":{
      "scriptId":"u12"},
    "cbc7c21ccabd4770bcc7e0b7f5ef4fba":{
      "scriptId":"u13"},
    "54896dc1a4454634ac9cb13dd1e9a025":{
      "scriptId":"u14"},
    "8490eb82861d479bb2fb15010bfe4ba5":{
      "scriptId":"u15"},
    "bef918f9625643199a1df3716b2edf00":{
      "scriptId":"u16"},
    "654dd0be9b68413595897709bf94bace":{
      "scriptId":"u17"},
    "0658abad21b246f9933473acf4fffc56":{
      "scriptId":"u18"},
    "0ba660e8465e4bf0a5dee07d0eb7c41b":{
      "scriptId":"u19"},
    "6a2835101dfe44e58bf154990c895518":{
      "scriptId":"u20"},
    "c68e641e11ea4d0280f9509210a329d8":{
      "scriptId":"u21"},
    "b21d23a4c0ae45d08d137a6a3011318d":{
      "scriptId":"u22"},
    "587c03ba440f43338cbc63312a45e6cc":{
      "scriptId":"u23"},
    "b5fa829a240f42f8afb6daae66a1e294":{
      "scriptId":"u24"},
    "a715fd4ada9f4b2da14511ab1409ba27":{
      "scriptId":"u25"},
    "a880a44ff69c46f9bf2eb12889897339":{
      "scriptId":"u26"},
    "614faad469f64774a979917d4d1f4c29":{
      "scriptId":"u27"},
    "740e52dbc92c47f1893af449f3297672":{
      "scriptId":"u28"},
    "5fb570b531d64d9988cfb9ffe3a6540c":{
      "scriptId":"u29"},
    "8309edd668bf4719834b54caaef1d271":{
      "scriptId":"u30"},
    "eb8b888d23af4951aafd91a7be01d63b":{
      "scriptId":"u31"},
    "2794ea5fa8364ed4a29de72e05d5f5ec":{
      "scriptId":"u32"},
    "074910347618419bb4f247a02d77cff8":{
      "scriptId":"u33"},
    "b9b704a4d8af4744b9e70e21bda13e55":{
      "scriptId":"u34"},
    "d4ea03eba8394b8dbb6d27e2eb76f144":{
      "scriptId":"u35"},
    "a21894adfe2849f5868cd97f14fa06e6":{
      "scriptId":"u36"}}});