$axure.loadCurrentPage({
  "url":"viewhistoryscore.html",
  "generationDate":new Date(1398842905873.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6c9687fda8e04829b1cf74e971add984",
    "type":"Axure:Page",
    "name":"ViewHistoryScore",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c37514994e114b308ffb81bd06b53626",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "size":{
                "width":1301,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF294590},
                  "size":{
                    "width":1301,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"f1138e4bb64a4b03a9c6dc5d544ec919",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"888ba27679964561b0d5cb2a0ef3c9b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u27.png"}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b79d47f0fac44b12b3883c52e1e972ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4B67AE},
              "location":{
                "x":203,
                "y":1},
              "size":{
                "width":73,
                "height":40},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73173e2d2f9942cc95bb9e59f7e1d295",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4B67AE},
                  "location":{
                    "x":203,
                    "y":1},
                  "size":{
                    "width":73,
                    "height":40},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u31.png"}},
{
            "id":"a19273aad5e84f14b1fa81e5785797c6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":202,
                "y":39},
              "size":{
                "width":74,
                "height":10}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaaab34ad5a9472aa24182c8c888f172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":202,
                    "y":39},
                  "size":{
                    "width":74,
                    "height":10}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u33.png"}},
{
            "id":"1087cb033ba644918269a0311bd5ab5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"9px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":431,
                "y":12},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce0a950f883342d4ab6d1be3cd0d810c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"9px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":431,
                    "y":12},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"59fe3b170417467e9815eada63bdbdf2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":221,
                "y":17},
              "size":{
                "width":37,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2003098ee0234a058a13919dad275e07",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":221,
                    "y":17},
                  "size":{
                    "width":37,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"131dcb64c5b64eaf9727db0ff5da22a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":304,
                "y":17},
              "size":{
                "width":43,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57955a7f69894cfe91133a475b6d8f6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":304,
                    "y":17},
                  "size":{
                    "width":43,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bebfd875fda4c26adb79875f309dca8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":393,
                "y":17},
              "size":{
                "width":35,
                "height":1}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8672a055a85f4a3ea48a54377f909e7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":393,
                    "y":17},
                  "size":{
                    "width":35,
                    "height":1}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ViewHistoryScore in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"viewhistoryscore.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4dc0d1b9cfb74e6ea7e30068da017d5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":474,
                "y":17},
              "size":{
                "width":54,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6599a0e13f6b4ea49a3d527489612b2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":17},
                  "size":{
                    "width":54,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "c37514994e114b308ffb81bd06b53626":{
      "scriptId":"u0",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u1"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u2"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u3"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u4"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u5"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u6"},
      "f1138e4bb64a4b03a9c6dc5d544ec919":{
        "scriptId":"u7"},
      "888ba27679964561b0d5cb2a0ef3c9b2":{
        "scriptId":"u8"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u9"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u10"},
      "b79d47f0fac44b12b3883c52e1e972ca":{
        "scriptId":"u11"},
      "73173e2d2f9942cc95bb9e59f7e1d295":{
        "scriptId":"u12"},
      "a19273aad5e84f14b1fa81e5785797c6":{
        "scriptId":"u13"},
      "eaaab34ad5a9472aa24182c8c888f172":{
        "scriptId":"u14"},
      "1087cb033ba644918269a0311bd5ab5c":{
        "scriptId":"u15"},
      "ce0a950f883342d4ab6d1be3cd0d810c":{
        "scriptId":"u16"},
      "59fe3b170417467e9815eada63bdbdf2":{
        "scriptId":"u17"},
      "2003098ee0234a058a13919dad275e07":{
        "scriptId":"u18"},
      "131dcb64c5b64eaf9727db0ff5da22a6":{
        "scriptId":"u19"},
      "57955a7f69894cfe91133a475b6d8f6f":{
        "scriptId":"u20"},
      "7bebfd875fda4c26adb79875f309dca8":{
        "scriptId":"u21"},
      "8672a055a85f4a3ea48a54377f909e7c":{
        "scriptId":"u22"},
      "4dc0d1b9cfb74e6ea7e30068da017d5b":{
        "scriptId":"u23"},
      "6599a0e13f6b4ea49a3d527489612b2a":{
        "scriptId":"u24"}}}});