$axure.loadCurrentPage({
  "url":"help.html",
  "generationDate":new Date(1404798818478.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6b94d6b33064f6cb12652d7889dce2c",
    "type":"Axure:Page",
    "name":"Help",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0cb16415acd04275a04cb05c2e46177e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":1300,
              "height":2000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332d0b61d87244d48097cae7a152eb1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":1300,
                  "height":2000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/viewhistoryscore/u0.png"}},
{
          "id":"023ee4da4046431e96ec1a6d3988e0e6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"},
{
          "id":"721f5c1cccaf48a7b2b4e9fe9a72edc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA3A3A3,
              "opacity":1},
            "location":{
              "x":0,
              "y":49},
            "size":{
              "width":1300,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE8E8E8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f1c23c90a64bb8b7886c67f402ad02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA3A3A3,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":49},
                "size":{
                  "width":1300,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE8E8E8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u4.png"}},
{
          "id":"f2882d9303a8432184161732f422bf48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":1120,
              "y":61},
            "size":{
              "width":170,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c955671c124a4d19870f4927e3894a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":1120,
                  "y":61},
                "size":{
                  "width":170,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f837240f2b3f4e8dadc00babeb03c578",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica-Light', 'Helvetica Light', 'Helvetica'",
            "fontSize":"24px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF717171,
              "opacity":1},
            "location":{
              "x":21,
              "y":67},
            "size":{
              "width":120,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e5522dc5ce422da84275a64000abbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica-Light', 'Helvetica Light', 'Helvetica'",
                "fontSize":"24px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF717171,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":67},
                "size":{
                  "width":120,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"255b5466958a4c5bba03de50a48bd02f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":65},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a46a53926549eaab8f1834e9f4b7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":65},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mainscreen/u263.png"}},
{
          "id":"68001362c8fc47c3aed9fc185d869658",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":50},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"67485eebc292442e9f52b9db6f3e62c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":80},
            "size":{
              "width":159,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7387f31c684b44f5a0c80f77bd749f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":80},
                "size":{
                  "width":159,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open MakeDecision in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"makedecision.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u261.png"}},
{
          "id":"5449b8dcb1714d4ab681eaa4514cb28c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":56},
            "size":{
              "width":190,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2b96f837581410181fb6f3a127e9b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":56},
                "size":{
                  "width":190,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u263.png"}},
{
          "id":"a7ddc98a26df493c83b35eb2fc9e8afa",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":50},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"f1cac654b0f2416fae03dc23abc08f06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":62},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"512b2d97cb6641c0b7cf99721bce689b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":62},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open VS in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/report/u266.png"}},
{
          "id":"a78539eace8b4aaaa58d03554d8066ab",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":49},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"11163017e49b46f6a1f9f7748e58dd45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF373737,
              "opacity":1},
            "location":{
              "x":757,
              "y":92},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34926e6bde1f4fff8b42efcf2189d1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana', 'Verdana'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF373737,
                  "opacity":1},
                "location":{
                  "x":757,
                  "y":92},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aef9682fb08d426ebf3f52606bbb247e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":62},
            "size":{
              "width":465,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61534c45aaaf428783cdeeeac2cdd9a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":62},
                "size":{
                  "width":465,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/report/u271.png"}},
{
          "id":"7518f48b78064c189557e1855a8c308a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":49},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDF0F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/report/u260_line.png"}},
{
          "id":"8423188487c24771921bfda31db6a16a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD3D4D9,
              "opacity":1},
            "location":{
              "x":360,
              "y":64},
            "size":{
              "width":300,
              "height":39}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1<br> (If length of value of widget This is greater than &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetValueLength",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}}},
{
          "id":"1341837ed7194991ad5b4b90716e04d8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":72},
            "size":{
              "width":45,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true},
{
          "id":"a731e16a678049628e25bc71cfb72899",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Verdana', 'Verdana'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6F6F6F,
              "opacity":1},
            "location":{
              "x":256,
              "y":69},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"38d9a16acdc84dd5827dc9bbc64ac31a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":160},
            "size":{
              "width":941,
              "height":1330}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"60067dad00ba4eb9beb56f0dce34b849",
              "label":"FAQ",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b525f098f15343a59c6792a451e2f1c4",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":900,
                      "height":840},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"925926346077461488feff34e8212e11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":900,
                          "height":840},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u53.png"}},
{
                  "id":"966448287e2c47ee89a1709b6fb80039",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5375E1},
                    "size":{
                      "width":160,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f519c6ebd4b489d8ca769f3e0680ccd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF5375E1},
                        "size":{
                          "width":160,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to FAQ",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u55.png"}},
{
                  "id":"faef20ff42014e94ad134e0bdc6e30ad",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "location":{
                      "x":157,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1abbe60511e3412cb4c676d16914d95b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "location":{
                          "x":157,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Video",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u57.png"}},
{
                  "id":"cda989f2099b40999fe1342c9840e5c3",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"470f6c58e56f4dd6b904ed45217fc968",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "location":{
                          "x":306,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Manual",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u57.png"}},
{
                  "id":"ac44509f360e4e14bb818747c7f3fce5",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":900,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF496ADC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/help/u61_line.png"}},
{
                  "id":"610bb6a4e9544389bba41fdadc84ef0f",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":68},
                    "size":{
                      "width":843,
                      "height":531}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c151238123d40d5a2f26e02520dcf64",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":68},
                        "size":{
                          "width":843,
                          "height":531}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u62.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c59c2be7f90548baa562dbb549cf9e45",
              "label":"Video",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"def6ef0168d44ff9a30ec046abaefaf0",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":900,
                      "height":840},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4dfc5550dff48b8844f0c7bd824be68",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":900,
                          "height":840},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u53.png"}},
{
                  "id":"49764a92b3144ba4a72bf91778ef0105",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "size":{
                      "width":160,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca3ec79413d94bcda3cfc55ef15f5be1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "size":{
                          "width":160,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to FAQ",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u66.png"}},
{
                  "id":"fab633983dc9490cb44f48ea0ca151b3",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5375E1},
                    "location":{
                      "x":157,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"690b401bb2164a7392afadf54393d82a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF5375E1},
                        "location":{
                          "x":157,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Video",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u68.png"}},
{
                  "id":"278e3495fd4d4e41a9e4747276db5a54",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10598b3f87f6462486553608ea4c247a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "location":{
                          "x":306,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Manual",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u57.png"}},
{
                  "id":"af9b5c35d8fa427aadee726f5b2f3f3d",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":900,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF496ADC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/help/u61_line.png"}},
{
                  "id":"d1b770fb57c84dd0807f57986707b7c4",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":117,
                      "y":103},
                    "size":{
                      "width":623,
                      "height":187}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a740a492a6a846a0af3bc9e9d02fbe59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":117,
                          "y":103},
                        "size":{
                          "width":623,
                          "height":187}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u73.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"208b8384da494c7cb21c960168d0b2b2",
              "label":"Manual",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7343607581bb4743808d5afbbe260b94",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":900,
                      "height":840},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5c4646a8334402288325e7f519b685e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":900,
                          "height":840},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u53.png"}},
{
                  "id":"90092d4d2fbd42ea85af81c262277a85",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "size":{
                      "width":160,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"779c75cba34a4232a6fcf4bef0ca9bb1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "size":{
                          "width":160,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to FAQ",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u66.png"}},
{
                  "id":"fd428c1fe5674781b67029b60af0476e",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF5375E1,
                      "opacity":1},
                    "location":{
                      "x":157,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cf2b717c7a645938bdb8c5af348076d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF5375E1,
                          "opacity":1},
                        "location":{
                          "x":157,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Video",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u57.png"}},
{
                  "id":"a6b9efe8bdcd4051afe750c6f468e88b",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5375E1},
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFEBEBEB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80fcfde368ff429c888f694b92dec31b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica-Bold', 'Helvetica Bold', 'Helvetica'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF5375E1},
                        "location":{
                          "x":306,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFEBEBEB}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Manual",
                              "panelsToStates":[{
                                  "panelPath":["38d9a16acdc84dd5827dc9bbc64ac31a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/help/u68.png"}},
{
                  "id":"1865a46b8cd94df59edf7e70f95630be",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":900,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF496ADC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/help/u61_line.png"}},
{
                  "id":"955cc818b1bb4f68a440ae18dcd870d8",
                  "label":"",
                  "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":70},
                    "size":{
                      "width":860,
                      "height":866}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6252d55ecf1a49a2b23e0fea7f6be845",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38d9a16acdc84dd5827dc9bbc64ac31a",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":70},
                        "size":{
                          "width":860,
                          "height":866}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/help/u84.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "size":{
                "width":1301,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF294590},
                  "size":{
                    "width":1301,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u1.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"f1138e4bb64a4b03a9c6dc5d544ec919",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"888ba27679964561b0d5cb2a0ef3c9b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u9.png"}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b79d47f0fac44b12b3883c52e1e972ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4B67AE},
              "location":{
                "x":203,
                "y":1},
              "size":{
                "width":73,
                "height":40},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73173e2d2f9942cc95bb9e59f7e1d295",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4B67AE},
                  "location":{
                    "x":203,
                    "y":1},
                  "size":{
                    "width":73,
                    "height":40},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u11.png"}},
{
            "id":"a19273aad5e84f14b1fa81e5785797c6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":202,
                "y":39},
              "size":{
                "width":74,
                "height":10}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaaab34ad5a9472aa24182c8c888f172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":202,
                    "y":39},
                  "size":{
                    "width":74,
                    "height":10}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/mainscreen/u13.png"}},
{
            "id":"59fe3b170417467e9815eada63bdbdf2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":221,
                "y":17},
              "size":{
                "width":37,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2003098ee0234a058a13919dad275e07",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":221,
                    "y":17},
                  "size":{
                    "width":37,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"131dcb64c5b64eaf9727db0ff5da22a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":304,
                "y":17},
              "size":{
                "width":43,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57955a7f69894cfe91133a475b6d8f6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":304,
                    "y":17},
                  "size":{
                    "width":43,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bebfd875fda4c26adb79875f309dca8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":393,
                "y":17},
              "size":{
                "width":35,
                "height":1}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8672a055a85f4a3ea48a54377f909e7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":393,
                    "y":17},
                  "size":{
                    "width":35,
                    "height":1}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ViewHistoryScore in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"viewhistoryscore.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4dc0d1b9cfb74e6ea7e30068da017d5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":474,
                "y":17},
              "size":{
                "width":54,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6599a0e13f6b4ea49a3d527489612b2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":17},
                  "size":{
                    "width":54,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1087cb033ba644918269a0311bd5ab5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"9px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":431,
                "y":12},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce0a950f883342d4ab6d1be3cd0d810c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"9px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":431,
                    "y":12},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "0cb16415acd04275a04cb05c2e46177e":{
      "scriptId":"u0"},
    "332d0b61d87244d48097cae7a152eb1f":{
      "scriptId":"u1"},
    "023ee4da4046431e96ec1a6d3988e0e6":{
      "scriptId":"u2",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u3"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u4"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u5"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u6"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u7"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u8"},
      "f1138e4bb64a4b03a9c6dc5d544ec919":{
        "scriptId":"u9"},
      "888ba27679964561b0d5cb2a0ef3c9b2":{
        "scriptId":"u10"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u11"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u12"},
      "b79d47f0fac44b12b3883c52e1e972ca":{
        "scriptId":"u13"},
      "73173e2d2f9942cc95bb9e59f7e1d295":{
        "scriptId":"u14"},
      "a19273aad5e84f14b1fa81e5785797c6":{
        "scriptId":"u15"},
      "eaaab34ad5a9472aa24182c8c888f172":{
        "scriptId":"u16"},
      "59fe3b170417467e9815eada63bdbdf2":{
        "scriptId":"u17"},
      "2003098ee0234a058a13919dad275e07":{
        "scriptId":"u18"},
      "131dcb64c5b64eaf9727db0ff5da22a6":{
        "scriptId":"u19"},
      "57955a7f69894cfe91133a475b6d8f6f":{
        "scriptId":"u20"},
      "7bebfd875fda4c26adb79875f309dca8":{
        "scriptId":"u21"},
      "8672a055a85f4a3ea48a54377f909e7c":{
        "scriptId":"u22"},
      "4dc0d1b9cfb74e6ea7e30068da017d5b":{
        "scriptId":"u23"},
      "6599a0e13f6b4ea49a3d527489612b2a":{
        "scriptId":"u24"},
      "1087cb033ba644918269a0311bd5ab5c":{
        "scriptId":"u25"},
      "ce0a950f883342d4ab6d1be3cd0d810c":{
        "scriptId":"u26"}},
    "721f5c1cccaf48a7b2b4e9fe9a72edc1":{
      "scriptId":"u27"},
    "58f1c23c90a64bb8b7886c67f402ad02":{
      "scriptId":"u28"},
    "f2882d9303a8432184161732f422bf48":{
      "scriptId":"u29"},
    "c955671c124a4d19870f4927e3894a2e":{
      "scriptId":"u30"},
    "f837240f2b3f4e8dadc00babeb03c578":{
      "scriptId":"u31"},
    "48e5522dc5ce422da84275a64000abbb":{
      "scriptId":"u32"},
    "255b5466958a4c5bba03de50a48bd02f":{
      "scriptId":"u33"},
    "31a46a53926549eaab8f1834e9f4b7d5":{
      "scriptId":"u34"},
    "68001362c8fc47c3aed9fc185d869658":{
      "scriptId":"u35"},
    "67485eebc292442e9f52b9db6f3e62c0":{
      "scriptId":"u36"},
    "7387f31c684b44f5a0c80f77bd749f77":{
      "scriptId":"u37"},
    "5449b8dcb1714d4ab681eaa4514cb28c":{
      "scriptId":"u38"},
    "c2b96f837581410181fb6f3a127e9b14":{
      "scriptId":"u39"},
    "a7ddc98a26df493c83b35eb2fc9e8afa":{
      "scriptId":"u40"},
    "f1cac654b0f2416fae03dc23abc08f06":{
      "scriptId":"u41"},
    "512b2d97cb6641c0b7cf99721bce689b":{
      "scriptId":"u42"},
    "a78539eace8b4aaaa58d03554d8066ab":{
      "scriptId":"u43"},
    "11163017e49b46f6a1f9f7748e58dd45":{
      "scriptId":"u44"},
    "34926e6bde1f4fff8b42efcf2189d1b4":{
      "scriptId":"u45"},
    "aef9682fb08d426ebf3f52606bbb247e":{
      "scriptId":"u46"},
    "61534c45aaaf428783cdeeeac2cdd9a9":{
      "scriptId":"u47"},
    "7518f48b78064c189557e1855a8c308a":{
      "scriptId":"u48"},
    "8423188487c24771921bfda31db6a16a":{
      "scriptId":"u49"},
    "1341837ed7194991ad5b4b90716e04d8":{
      "scriptId":"u50"},
    "a731e16a678049628e25bc71cfb72899":{
      "scriptId":"u51"},
    "38d9a16acdc84dd5827dc9bbc64ac31a":{
      "scriptId":"u52"},
    "b525f098f15343a59c6792a451e2f1c4":{
      "scriptId":"u53"},
    "925926346077461488feff34e8212e11":{
      "scriptId":"u54"},
    "966448287e2c47ee89a1709b6fb80039":{
      "scriptId":"u55"},
    "9f519c6ebd4b489d8ca769f3e0680ccd":{
      "scriptId":"u56"},
    "faef20ff42014e94ad134e0bdc6e30ad":{
      "scriptId":"u57"},
    "1abbe60511e3412cb4c676d16914d95b":{
      "scriptId":"u58"},
    "cda989f2099b40999fe1342c9840e5c3":{
      "scriptId":"u59"},
    "470f6c58e56f4dd6b904ed45217fc968":{
      "scriptId":"u60"},
    "ac44509f360e4e14bb818747c7f3fce5":{
      "scriptId":"u61"},
    "610bb6a4e9544389bba41fdadc84ef0f":{
      "scriptId":"u62"},
    "4c151238123d40d5a2f26e02520dcf64":{
      "scriptId":"u63"},
    "def6ef0168d44ff9a30ec046abaefaf0":{
      "scriptId":"u64"},
    "b4dfc5550dff48b8844f0c7bd824be68":{
      "scriptId":"u65"},
    "49764a92b3144ba4a72bf91778ef0105":{
      "scriptId":"u66"},
    "ca3ec79413d94bcda3cfc55ef15f5be1":{
      "scriptId":"u67"},
    "fab633983dc9490cb44f48ea0ca151b3":{
      "scriptId":"u68"},
    "690b401bb2164a7392afadf54393d82a":{
      "scriptId":"u69"},
    "278e3495fd4d4e41a9e4747276db5a54":{
      "scriptId":"u70"},
    "10598b3f87f6462486553608ea4c247a":{
      "scriptId":"u71"},
    "af9b5c35d8fa427aadee726f5b2f3f3d":{
      "scriptId":"u72"},
    "d1b770fb57c84dd0807f57986707b7c4":{
      "scriptId":"u73"},
    "a740a492a6a846a0af3bc9e9d02fbe59":{
      "scriptId":"u74"},
    "7343607581bb4743808d5afbbe260b94":{
      "scriptId":"u75"},
    "f5c4646a8334402288325e7f519b685e":{
      "scriptId":"u76"},
    "90092d4d2fbd42ea85af81c262277a85":{
      "scriptId":"u77"},
    "779c75cba34a4232a6fcf4bef0ca9bb1":{
      "scriptId":"u78"},
    "fd428c1fe5674781b67029b60af0476e":{
      "scriptId":"u79"},
    "9cf2b717c7a645938bdb8c5af348076d":{
      "scriptId":"u80"},
    "a6b9efe8bdcd4051afe750c6f468e88b":{
      "scriptId":"u81"},
    "80fcfde368ff429c888f694b92dec31b":{
      "scriptId":"u82"},
    "1865a46b8cd94df59edf7e70f95630be":{
      "scriptId":"u83"},
    "955cc818b1bb4f68a440ae18dcd870d8":{
      "scriptId":"u84"},
    "6252d55ecf1a49a2b23e0fea7f6be845":{
      "scriptId":"u85"}}});