$axure.loadCurrentPage({
  "url":"companyinfo.html",
  "generationDate":new Date(1398839127793.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"16866319110f4143b55a1e3367d82b41",
    "type":"Axure:Page",
    "name":"CompanyInfo",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9e5001dcb93a4d9bb9c31395ed027f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":151},
            "size":{
              "width":1060,
              "height":690},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE0E0E0}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e0a3c97b71a4e1dbea70ea5fc4f78b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":151},
                "size":{
                  "width":1060,
                  "height":690},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE0E0E0}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/companyinfo/u0.png"}},
{
          "id":"d662a2c7ee404d6998b4d7e7aa5d9c13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":89},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba757d9896324f55bd3f5e5274c8172f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":89},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1732bfabdde4656b403edb9659e9b37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":167},
            "size":{
              "width":242,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851d3fb7fab74122a8a1429ff0bf39b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":167},
                "size":{
                  "width":242,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/companyinfo/u4.png"}},
{
          "id":"15f83b2e9d94406ea105f897edec9ee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":350,
              "y":167},
            "size":{
              "width":48,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d2e1b6ab3d4f5aaaa3f89546251648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":350,
                  "y":167},
                "size":{
                  "width":48,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760a03aead7c4ad0a28ae594e3d40eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":442,
              "y":167},
            "size":{
              "width":85,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b6a1bb9caae493c8d2db2675b9f4964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":442,
                  "y":167},
                "size":{
                  "width":85,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6cbc8de0d2141f8b72c41bc25d29cec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":447},
            "size":{
              "width":713,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/companyinfo/u10_line.png"}},
{
          "id":"f6b632111280459abd7cbb418b76bba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":327,
              "y":427},
            "size":{
              "width":201,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28af1cac2bea43da8d58b5c1f11582d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":327,
                  "y":427},
                "size":{
                  "width":201,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aaf4110b885486d960d513b4d42ae5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":400,
              "y":237},
            "size":{
              "width":484,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73115d746a34bd880f5fda8c3ae00df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":400,
                  "y":237},
                "size":{
                  "width":484,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e902c06d1d9a4049b5a2ef0edd28fbaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":487},
            "size":{
              "width":131,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62de8a40cd2f4401905a19431508780e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":487},
                "size":{
                  "width":131,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f041748ebae428dbdd5ca6d0564fecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":487},
            "size":{
              "width":131,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc06f95e71084872b605b66f9f79f28e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":487},
                "size":{
                  "width":131,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"956359233c1e4e1399a45a47285131c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":487},
            "size":{
              "width":131,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3935d9f8872543f0aa5488fe31482fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":487},
                "size":{
                  "width":131,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3059d9d3d534ba9a1dbcc35de5ffb42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":487},
            "size":{
              "width":131,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1389fcb03d914049bab13125d8b5e899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":779,
                  "y":487},
                "size":{
                  "width":131,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae4bfdd16dbe4d86969941391932870c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":487},
            "size":{
              "width":131,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c1700842494a2cb021fd6854fe4510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":487},
                "size":{
                  "width":131,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ac4a22c42e54bb4b6b9de58d7f281f1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":747},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open MainScreen in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mainscreen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5bb2898955994d3da1226e4f84694abf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"035c62c2c750447e98a63f8ee7e436bc"}]}},
  "masters":{
    "035c62c2c750447e98a63f8ee7e436bc":{
      "packageId":"035c62c2c750447e98a63f8ee7e436bc",
      "type":"Axure:Master",
      "name":"UserMainHeader",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0109c286a65a41d0809502b02b37fe83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "size":{
                "width":1301,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF2CAA3F},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"af79783402e44ac98fc3741bd58e0c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF294590},
                  "size":{
                    "width":1301,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF2CAA3F},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u21.png"}},
{
            "id":"41d1bcdce1d4449197b8ef6bc945805e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":1169,
                "y":17},
              "size":{
                "width":111,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b57c0ce0279342d986c17ef400fd56c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":1169,
                    "y":17},
                  "size":{
                    "width":111,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open AboutMarkSimos in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"aboutmarksimos.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"74fa8247db3e4b6f8453ffb34c871b0f",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":1089,
                "y":12},
              "size":{
                "width":60,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"77c6f28e54a5492fadf43be9f0899f49",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF294590},
              "location":{
                "x":960,
                "y":12},
              "size":{
                "width":100,
                "height":22}},
            "adaptiveStyles":{
}},
{
            "id":"f1138e4bb64a4b03a9c6dc5d544ec919",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":11},
              "size":{
                "width":42,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"888ba27679964561b0d5cb2a0ef3c9b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":11},
                  "size":{
                    "width":42,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u27.png"}},
{
            "id":"5b177912dc8146e796017c8c72004b73",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":72,
                "y":16},
              "size":{
                "width":75,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"824235d615994e0bb58a7c2c6e80171a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":16},
                  "size":{
                    "width":75,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b79d47f0fac44b12b3883c52e1e972ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4B67AE},
              "location":{
                "x":203,
                "y":1},
              "size":{
                "width":73,
                "height":40},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73173e2d2f9942cc95bb9e59f7e1d295",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4B67AE},
                  "location":{
                    "x":203,
                    "y":1},
                  "size":{
                    "width":73,
                    "height":40},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u31.png"}},
{
            "id":"a19273aad5e84f14b1fa81e5785797c6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":202,
                "y":39},
              "size":{
                "width":74,
                "height":10}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eaaab34ad5a9472aa24182c8c888f172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":202,
                    "y":39},
                  "size":{
                    "width":74,
                    "height":10}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/introduction/u33.png"}},
{
            "id":"1087cb033ba644918269a0311bd5ab5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"9px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":431,
                "y":12},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce0a950f883342d4ab6d1be3cd0d810c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"9px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":431,
                    "y":12},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"59fe3b170417467e9815eada63bdbdf2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":221,
                "y":17},
              "size":{
                "width":37,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2003098ee0234a058a13919dad275e07",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":221,
                    "y":17},
                  "size":{
                    "width":37,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MainScreen in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"mainscreen.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"131dcb64c5b64eaf9727db0ff5da22a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":304,
                "y":17},
              "size":{
                "width":43,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"57955a7f69894cfe91133a475b6d8f6f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":304,
                    "y":17},
                  "size":{
                    "width":43,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Report in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"report.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bebfd875fda4c26adb79875f309dca8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":393,
                "y":17},
              "size":{
                "width":35,
                "height":1}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8672a055a85f4a3ea48a54377f909e7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":393,
                    "y":17},
                  "size":{
                    "width":35,
                    "height":1}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ViewHistoryScore in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"viewhistoryscore.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4dc0d1b9cfb74e6ea7e30068da017d5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
              "fontSize":"11px",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCFD9F3,
                "opacity":1},
              "location":{
                "x":474,
                "y":17},
              "size":{
                "width":54,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6599a0e13f6b4ea49a3d527489612b2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Verdana-Bold', 'Verdana Bold', 'Verdana'",
                  "fontSize":"11px",
                  "fontWeight":"700",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCFD9F3,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":17},
                  "size":{
                    "width":54,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open MakeDecision in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"makedecision.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9e5001dcb93a4d9bb9c31395ed027f07":{
      "scriptId":"u0"},
    "5e0a3c97b71a4e1dbea70ea5fc4f78b9":{
      "scriptId":"u1"},
    "d662a2c7ee404d6998b4d7e7aa5d9c13":{
      "scriptId":"u2"},
    "ba757d9896324f55bd3f5e5274c8172f":{
      "scriptId":"u3"},
    "a1732bfabdde4656b403edb9659e9b37":{
      "scriptId":"u4"},
    "851d3fb7fab74122a8a1429ff0bf39b2":{
      "scriptId":"u5"},
    "15f83b2e9d94406ea105f897edec9ee2":{
      "scriptId":"u6"},
    "64d2e1b6ab3d4f5aaaa3f89546251648":{
      "scriptId":"u7"},
    "760a03aead7c4ad0a28ae594e3d40eea":{
      "scriptId":"u8"},
    "3b6a1bb9caae493c8d2db2675b9f4964":{
      "scriptId":"u9"},
    "a6cbc8de0d2141f8b72c41bc25d29cec":{
      "scriptId":"u10"},
    "f6b632111280459abd7cbb418b76bba6":{
      "scriptId":"u11"},
    "28af1cac2bea43da8d58b5c1f11582d5":{
      "scriptId":"u12"},
    "9aaf4110b885486d960d513b4d42ae5e":{
      "scriptId":"u13"},
    "c73115d746a34bd880f5fda8c3ae00df":{
      "scriptId":"u14"},
    "e902c06d1d9a4049b5a2ef0edd28fbaf":{
      "scriptId":"u15"},
    "62de8a40cd2f4401905a19431508780e":{
      "scriptId":"u16"},
    "6f041748ebae428dbdd5ca6d0564fecf":{
      "scriptId":"u17"},
    "cc06f95e71084872b605b66f9f79f28e":{
      "scriptId":"u18"},
    "956359233c1e4e1399a45a47285131c2":{
      "scriptId":"u19"},
    "3935d9f8872543f0aa5488fe31482fcc":{
      "scriptId":"u20"},
    "c3059d9d3d534ba9a1dbcc35de5ffb42":{
      "scriptId":"u21"},
    "1389fcb03d914049bab13125d8b5e899":{
      "scriptId":"u22"},
    "ae4bfdd16dbe4d86969941391932870c":{
      "scriptId":"u23"},
    "40c1700842494a2cb021fd6854fe4510":{
      "scriptId":"u24"},
    "7ac4a22c42e54bb4b6b9de58d7f281f1":{
      "scriptId":"u25"},
    "5bb2898955994d3da1226e4f84694abf":{
      "scriptId":"u26",
      "0109c286a65a41d0809502b02b37fe83":{
        "scriptId":"u27"},
      "af79783402e44ac98fc3741bd58e0c32":{
        "scriptId":"u28"},
      "41d1bcdce1d4449197b8ef6bc945805e":{
        "scriptId":"u29"},
      "b57c0ce0279342d986c17ef400fd56c7":{
        "scriptId":"u30"},
      "74fa8247db3e4b6f8453ffb34c871b0f":{
        "scriptId":"u31"},
      "77c6f28e54a5492fadf43be9f0899f49":{
        "scriptId":"u32"},
      "f1138e4bb64a4b03a9c6dc5d544ec919":{
        "scriptId":"u33"},
      "888ba27679964561b0d5cb2a0ef3c9b2":{
        "scriptId":"u34"},
      "5b177912dc8146e796017c8c72004b73":{
        "scriptId":"u35"},
      "824235d615994e0bb58a7c2c6e80171a":{
        "scriptId":"u36"},
      "b79d47f0fac44b12b3883c52e1e972ca":{
        "scriptId":"u37"},
      "73173e2d2f9942cc95bb9e59f7e1d295":{
        "scriptId":"u38"},
      "a19273aad5e84f14b1fa81e5785797c6":{
        "scriptId":"u39"},
      "eaaab34ad5a9472aa24182c8c888f172":{
        "scriptId":"u40"},
      "1087cb033ba644918269a0311bd5ab5c":{
        "scriptId":"u41"},
      "ce0a950f883342d4ab6d1be3cd0d810c":{
        "scriptId":"u42"},
      "59fe3b170417467e9815eada63bdbdf2":{
        "scriptId":"u43"},
      "2003098ee0234a058a13919dad275e07":{
        "scriptId":"u44"},
      "131dcb64c5b64eaf9727db0ff5da22a6":{
        "scriptId":"u45"},
      "57955a7f69894cfe91133a475b6d8f6f":{
        "scriptId":"u46"},
      "7bebfd875fda4c26adb79875f309dca8":{
        "scriptId":"u47"},
      "8672a055a85f4a3ea48a54377f909e7c":{
        "scriptId":"u48"},
      "4dc0d1b9cfb74e6ea7e30068da017d5b":{
        "scriptId":"u49"},
      "6599a0e13f6b4ea49a3d527489612b2a":{
        "scriptId":"u50"}}}});